docs/integrations/S3/s3-merge-tree.md, docs/integrations/S3/s3-minio.md, docs/integrations/S3/s3-optimizing-performance.md
Request a review from @kssenii @nikitamikhaylov @alesapin
=> more s3 internals

docs/integrations/s3/s3-merge-tree.md
=> S3 internals

docusaurus.config.js
=> feat(config): use svg logo in footer

docs/en/guides/sre/ssl-user-auth.md
SSL User certificate Auth. 
not sure if I should add the File users method since i believe we're moving away from that.
=> Initial SSL User Auth doc

docs/en/guides/sre/clickhouse-keeper.md
=> Fix spelling of ZooKeeper

docs/en/integrations/dbt/dbt-snapshot.md
=> remove extra parens

docs/en/about-us/adopters.md, docs/en/faq/operations/index.md, docs/en/guides/sre/keeper/clickhouse-keeper.md
Updated adopters: added 4 new adopters
=> Updated adopters: added 4 new adopters

docs/en/guides/sre/keeper/clickhouse-keeper.md
tweaking Algolia, adding description
=> add description front matter

docs/en/integrations/s3/s3-merge-tree.md
There was a mistake initially of  'attraction' instead of 'attractive', but I also think it will be a bit better after my other changes.
=> A minor wording change

docs/en/guides/developer/working-with-json/json-other-approaches.md
Fix 2 links to corresponding function page and anchor
=> Fix links JSON_QUERY & JSON_VALUE

docs/en/integrations/s3/s3-merge-tree.md, docusaurus.config.js, src/css/custom.css, static/img/logo_without_text.svg
- Add dark mode
- Update CSS to add a white background behind images (we have some transparent images)
- Fix shadows in Light mode
=> Add dark mode 

src/css/custom.css
=> fix color of > in menu

src/css/custom.css
background color for images needs to be white for dark mode.
color of top area of homepage needs to be transparent
=> fix colors on docs homepage

docs/en/guides/sre/configuring-s3-for-clickhouse-use.md
=> add S3 guide

docusaurus.config.js, src/css/custom.css
Needed CSS in addition to setting hideOnScroll
=> Fix hide on scroll

docs/en/about-us/adopters.md
=> add explo.co to adopters

docs/en/integrations/index.mdx
I reused a CSS class that was created for the adopters table to fix the table width
`<div class="adopters-table">`
=> Fixed tables width for integrations

docs/en/guides/sre/s3-multi-region.md, docs/en/integrations/data-ingestion/s3/s3-merge-tree.md, docs/en/integrations/data-ingestion/s3/s3-optimizing-performance.md
@alexey-milovidov @tbragin please review.  Thanks very much.
=> update docs for  zero copy replication setting change

docs/en/about-us/adopters.md, docs/en/about-us/support.md, docs/en/whats-new/changelog/2017.md, docs/en/whats-new/changelog/2018.md, docs/en/whats-new/changelog/2019.md, docs/en/whats-new/changelog/2020.md, docs/en/whats-new/changelog/2021.md, docs/en/whats-new/changelog/index.md, docs/en/whats-new/roadmap.md, docs/ru/about-us/adopters.md, docs/ru/about-us/support.md, docs/ru/whats-new/changelog/2017.md, docs/ru/whats-new/changelog/2018.md, docs/ru/whats-new/changelog/2019.md, docs/ru/whats-new/changelog/2020.md, docs/ru/whats-new/changelog/2021.md, docs/ru/whats-new/changelog/index.md, docs/ru/whats-new/roadmap.md
Do not merge until updates in ClickHouse/ClickHouse are made
=> HOLD: remove symlinks, use MDX import

docs/en/integrations/data-ingestion/kafka/kafka-table-engine.md
1. The insert statement in Inserting rows directly is error and it hasn't sql wrapper;
2. There isn't CREATE TABLE statement in Utilizing-materialized-views, it would cause the Syntax error.
=> Fix sql statement and add sql wrapper

docs/en/faq/general/columnar-database.md
=> switch to relative link

docs/en/guides/developer/full-text-search.md
Regarding the issue #288 The command needs to be updated.
link: https://github.com/ClickHouse/clickhouse-docs/issues/288
=> Updating the Clickhouse Full Text Search doc

docs/en/integrations/data-ingestion/kafka/kafka-connect-jdbc.md
Changed some link like "..integrations/kafka/.." to "..integrations/data-ingestion/kafka/.."
=> Fix link is invalid.

docs/en/integrations/migration/remotesecure.md
closes https://github.com/ClickHouse/clickhouse-docs/issues/295
We can hold this for a while, or publish now.
=> add remoteSecure guide

docs/en/faq/operations/production.md
- It's related to this [PR](https://github.com/ClickHouse/ClickHouse/pull/41071).
=> Remove strange trains description

docs/en/_snippets/_gather_your_details_native.md
=> update native TCP connection details

docs/en/faq/operations/delete-old-data.md
@blinkov can I also update the distinctive features and remove the [line about deletes](https://github.com/ClickHouse/clickhouse-docs/blob/main/docs/en/about-us/distinctive-features.md?plain=1#L95)?
closes #366
=> update faq regarding deletes

docs/en/guides/sre/configuring-ssl.md
closes https://github.com/ClickHouse/ClickHouse/issues/38188
=> add testing for Keeper

docs/en/integrations/data-ingestion/s3/s3-table-engine.md
- fix bucket URL
- fix list at end of doc
- change query, the records in this subset only have unknown payment type, so the old query is not interesting.
=> update s3 example using NYC Taxi data

docs/en/quick-start.mdx
=> update vis url

docusaurus.config.js
Do not merge until test passes
=> temp fix for manage security

docs/en/manage/billing.md
=> move examples up

docusaurus.config.js
=> redir install to combined requirements and install doc

docs/en/manage/tuning-for-cloud-cost-efficiency.md
=> update cost saving doc

docs/en/faq/billing.md, docs/en/manage/billing.md
@gjones duplicates Manage > Billing to FAQ > Billing
=> add billing to faq

docs/en/manage/tuning-for-cloud-cost-efficiency.md
Warning that Automatic deduplication is disabled for asynchronous inserts
=> Warning that Automatic deduplication is disabled for asynchronous inserts

docs/en/integrations/sql-clients/arctype.md
=> mark Arctype download EOL

src/css/custom.css
Let's see what damage this does
=> 404 header color

docs/en/manage/scaling.mdx
closes https://github.com/ClickHouse/product/issues/567
=> Remove image from autoscaling doc

docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-multiple.md
=> change "one if" to "one of"

docs/en/integrations/data-ingestion/s3/s3-intro.md
Because the docs are presented as a series of pages that the reader clicks through, the word "below" felt a bit confusing!
=> Clarify verbiage

docusaurus.config.js, src/css/custom.css
=> add try for free link

docs/en/whats-new/cloud-capabilities.md
=> add max_parts_in_total to Cloud Compatibility

docs/en/whats-new/changelog/cloud.md
=> October 25th release notes

docs/en/guides/sre/user-management/access-rights.mdx, docs/en/tutorial.md, docusaurus.config.js, sidebars.js
The page https://clickhouse.com/docs/en/operations/access-rights/ was missing a sidebar.
cc: @cwurm
=> Update user management

docs/en/manage/update.mdx, docusaurus.config.js
Must be merged after (with) https://github.com/ClickHouse/ClickHouse/pull/42877
closes #508
=> add redir for old update page

docs/en/about-us/adopters.md
Favicons were broken while migrating to the new docs.
I don't see anyone cares.
This PRs removing the garbage.
=> Favicons don't work anyway

docs/en/whats-new/security-changelog.md
As per Martin's comment, I'm just updating these lines to keep the version numbering consistent
=> Fix CH version

docs/en/integrations/language-clients/python/intro.md
As title, removing and adding some typos.
=> Fix typo for the example code and descriptions

README.md
As title, the original link is not found. Using the correct logo link.
=> Fix image logo link

docs/en/integrations/data-ingestion/s3/s3-merge-tree.md, docs/en/integrations/data-ingestion/s3/s3-table-functions.md
=> use full path, .md, and slash before anchor

docs/en/quick-start.mdx, sidebars.js
Updates to sidebars for two operations dirs that have index pages
Update the next page from quick-start
=> Fix pagination

docs/en/integrations/language-clients/nodejs.md
Add an example of module importing for env without ESM support
=> [nodejs client] Add an example of module importing for env without ESM support

docs/en/faq/troubleshooting.md, docs/en/manage/security/ip-access-list.md
@rfraposa please merge after the update later this week. @bianpengyuan please ping Rich.
=> update response from Cloud when Access List does not include host

docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-design.md
Article introduction consisting of over a dozen paragraphs was hard to follow.
=> Condense intro in "ClickHouse Index Design"

.github/CODEOWNERS
Add CODEOWNERS file https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
and ping  @ClickHouse/integrations  team on changes in `integrations` folder
=> add codeowners file.

docs/en/integrations/data-ingestion/kafka/kafka-choosing-an-approach.md, docs/en/integrations/data-ingestion/kafka/kafka-table-engine.md, docs/en/integrations/data-ingestion/s3/configuring-s3-for-clickhouse-use.md, docs/en/integrations/data-ingestion/s3/s3-intro.md, docs/en/integrations/data-ingestion/s3/s3-merge-tree.md, docs/en/integrations/data-ingestion/s3/s3-minio.md, docs/en/integrations/data-ingestion/s3/s3-multi-region.md, docs/en/integrations/data-ingestion/s3/s3-optimizing-performance.md, docs/en/integrations/data-ingestion/s3/s3-table-engine.md
@Ryado Can you have a look at these edits please?
=> add cloud support notes

docs/en/guides/sre/user-management/users-and-roles.md
@e-mars ready for testing.  I tested the Cloud flow.  Thanks so much for this great information.
=> use new default_role for SQL user doc

sidebars.js
=> add ssl info to replication

docs/en/faq/use-cases/time-series.md, docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-cardinality.md, docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-intro.md, docs/en/integrations/data-ingestion/dbms/postgresql/postgres-with-clickhouse.md, docs/en/integrations/data-ingestion/etl-tools/vector-to-clickhouse.md, docs/en/integrations/data-ingestion/insert-local-files.md, docs/en/integrations/data-ingestion/kafka/kafka-clickhouse-connect-sink.md, docs/en/integrations/data-ingestion/kafka/kakfa-intro.md, docs/en/integrations/data-visualization/grafana-and-clickhouse.md, docs/en/integrations/data-visualization/metabase-and-clickhouse.md, docs/en/integrations/data-visualization/superset-and-clickhouse.md
Fairly aggressively linked here and updated format.
@tbragin I know you've been doing this as well. Brings us up-to-date.
=> Blog links

docs/en/integrations/data-ingestion/s3/s3-merge-tree.md
=> update to new cachec settings

docs/en/integrations/data-ingestion/s3/configuring-s3-for-clickhouse-use.md, docs/en/integrations/data-ingestion/s3/s3-merge-tree.md, docs/en/integrations/data-ingestion/s3/s3-multi-region.md
the cache system was changed, updating pages @e-mars
=> Update cache s3 multi region

docs/en/integrations/data-formats.md, docs/en/integrations/data-ingestion/data-formats/_category_.yml, docs/en/integrations/data-ingestion/data-formats/json.md
=> add intro for formats

docs/en/integrations/data-ingestion/s3/s3-minio.md
closes https://github.com/ClickHouse/ClickHouse/issues/45434
=> docs update cache for minio

docs/en/guides/developer/cascading-materialized-views.md
@CamiloSierraH I will run through this and add output for the test queries, let me know if there are other docs that we should point to in the more info and any changes that you want.
=> Add docs for cascading materialized view

docs/en/guides/developer/ttl.md
Including removing rows, removing columns, rolling up data, and an example of a hot/warm/cold architecture
=> Create a new guide for using TTL

docs/en/integrations/data-ingestion/kafka/kafka-clickhouse-connect-sink.md, docs/en/integrations/index.mdx
follow-up on https://github.com/ClickHouse/clickhouse-docs/pull/717
=> Tablum to partner integrations

docs/en/guides/developer/lightweight-delete.md
depends on https://github.com/ClickHouse/ClickHouse/pull/46015
=> Added Lightweight Delete internals

package.json, yarn.lock
version 2.3.1 broke our swizzle of DocCard again
=> freeze version

docusaurus.config.js, package.json, yarn.lock
Add diagrams like this:
This is the markdown for the above:
<pre>
```mermaid
graph TD;
A-->B;
A-->C;
B-->D;
C-->D;
```
</pre
=> add mermaid diagram support

.htmltest.yml
=> check all external URLs

docusaurus.config.js, package.json, yarn.lock
Replaces #249 
@rschu1ze 
This in a markdown file:
```md
$$
I = \int_0^{2\pi} \sin(x)\,dx
$$
or
Let $f\colon[a,b]\to\R$ be Riemann integrable. Let $F\colon[a,b]\to\R$ be
$F(x)=\int_{a}^{x} f(t)\,dt$. Then $F$ is continuous, and at all $x$ such that
```
Renders as:
=> add katex support

src/css/custom.css
It's been broken for a while - this should fix it.
=> Fix top margin of the search results page

docs/en/integrations/index.mdx
@DanRoscigno I am adding rows for partners and community projects that stood out to me to the table in the Integrations page. Note that icons are missing - hopefully we can add them later. 
I am sure there are more - overtime we can add them as well or ask folks in the company / community to contribute. 
cc @tylerhannan @alexey-milovidov @Ryado
=> Update integrations index.mdx

docs/en/integrations/index.mdx
@alexey-milovidov @DanRoscigno @Ryado Another PR for a few more partner and community integrations
=> Update integrations index.mdx - Part 2

docs/en/guides/developer/cascading-materialized-views.md
@rfraposa as discussed in docs sync
closes https://github.com/ClickHouse/ClickHouse/issues/7195
=> Rename from Cascading Materialized Views

docs/en/integrations/language-clients/go/intro.md
closes https://github.com/ClickHouse/clickhouse-docs/issues/443
=> add golang MVP

docs/en/about-us/adopters.md
=> adding adopters

docs/en/faq/operations/production.md, docs/en/integrations/data-ingestion/s3/s3-minio.md, docs/en/integrations/language-clients/nodejs.md, docs/en/integrations/sql-clients/tablum.md, docs/en/native-protocol/basics.md, docs/en/native-protocol/hash.md, docs/en/native-protocol/server.md
Many of the admonitions are severe, where a tip, note, info, or important is appropriate.  Lets use warning when there is risk of data loss or system crash.
=> standardize admonitions

docs/en/faq/operations/delete-old-data.md
=> fix intermittent 404

docs/en/faq/operations/production.md, docs/en/integrations/data-ingestion/s3/s3-minio.md, docs/en/integrations/language-clients/nodejs.md, docs/en/integrations/sql-clients/tablum.md, docs/en/native-protocol/basics.md, docs/en/native-protocol/hash.md, docs/en/native-protocol/server.md
Reverts ClickHouse/clickhouse-docs#890
=> Revert "standardize admonitions"

docs/en/integrations/language-clients/nodejs.md
See https://github.com/ClickHouse/clickhouse-js/pull/139
=> Update Node.js docs for 0.0.13

src/css/default.scss
Fixes https://github.com/ClickHouse/ClickHouse/issues/47698
=> Fix background highlighting

knowledgebase/s3_export_data_year_month_folders.md
KB on How can I do partitioned writes by year and month on S3?
=> [KB] How can I do partitioned writes by year and month on S3?

knowledgebase/how_to_display_queries_using_MV.md
KB article on What queries are using Materialized Views?
=> [KB] What queries are using Materialized Views?

knowledgebase/importing_and_working_with_JSON_array_objects.md
KB article on Importing and querying JSON array objects
=> [KB] Importing and querying JSON array objects

docusaurus.config.js
Link was wrong...generating a 404
=> Fix /en/manage/security

docs/en/guides/sre/user-management/ssl-user-auth.md
https://github.com/ClickHouse/ClickHouse/pull/47596
=> Add native protocol example to SSL User Certificate Authentication

knowledgebase/s3_export_data_year_month_folders.md
PR that removes compression [parameter](https://github.com/ClickHouse/clickhouse-docs/blame/main/knowledgebase/s3_export_data_year_month_folders.md#L65) (file extension defines it) from S3 partitioned writes KB
=> [KB] gz extension defines compression

docs/en/cloud/security/ip-egress-traffic-list.md
- Updating the example to the new format
- Related https://github.com/ClickHouse/data-plane-application/issues/2423
=> Update public ips api example

docs/en/integrations/data-ingestion/gcs/index.md, docs/en/integrations/data-ingestion/s3/index.md
closes #545 
@e-mars : FYI: For Keeper `apt install clickhouse-keeper`, no more creating dirs by hand, and `systemctl enable` etc. works.
=> update to use systemctl for keeper

sidebars.js
It's just below clickhouse-client
=> Add clickhouse-local to sidebar nav

src/css/colors.scss, src/css/custom.scss
=> Fixing colour issues.

docs/en/intro.md
Reverts ClickHouse/clickhouse-docs#990
=> Revert "Update intro.md"

knowledgebase/importing_and_working_with_JSON_array_objects.md
fixes couple of incosistencies in KB
=> [KB] Fix json kb inconsistencies

docs/en/guides/sre/user-management/index.md
Include the recommended solution from this [issue](https://github.com/ClickHouse/ClickHouse/issues/47092) in the use management documentation.
=> Update User Management Documentation

docs/en/about-us/adopters.md
Adding resmo per https://clickhouse.com/blog/how-we-used-clickhouse-to-store-opentelemetry-traces
=> Adding Resmo

knowledgebase/install-clickhouse-windows10.md
this PR adds Windows WSL install steps.
=> Windows 10 install KB

docs/en/integrations/data-ingestion/etl-tools/dbt/index.md
Change documentation to reflect that ephemeral materializations are supported by dbt-clickhouse.
Solves #1072
=> Update dbt-clickhouse documentation

docs/en/integrations/data-ingestion/kafka/index.md
Adding some additional troubleshooting steps based on recent changes and customer questions.
=> Updating the kafka-connect docs to add some troubleshooting steps

knowledgebase/compare_resultsets.md
KB on "How can I validate that two queries return the same resultsets?"
=> [KB] Comparing resultsets between queries

docs/en/about-us/adopters.md
=> Adding numerous adopters

knowledgebase/json_extract_example.md
=> [KB] json_extract example

docs/en/integrations/language-clients/python/index.md
Plus new section on multi threading.
=> Update clickhouse-connect docs for version 0.5.24 

docs/en/integrations/data-ingestion/kafka/index.md
kafkacat command is now renamed to kcat
=> kafkacat command is now renamed to kcat

sidebars.js
closes https://github.com/ClickHouse/ClickHouse/issues/50158
=> fix nav for formats

src/theme/DocItem/TOC/Desktop/index.js
https://clickhouse-docs-git-38-increase-cloud-presenc-a3e39f-clickhouse.vercel.app/docs/en/intro
=> Update sessionStorage to localStorage for saving banner close state

docs/en/integrations/data-visualization/grafana-and-clickhouse.md
=> add Grafana / Cloud video

knowledgebase/check-query-cache-in-use.md
[KB] How to check query cache is used
=> [KB] How to check query cache is used

docs/en/_snippets/_keeper-config-files.md, docs/en/deployment-guides/replicated.md
closes https://github.com/ClickHouse/ClickHouse/issues/50694
=> Fix keeper example

docs/en/about-us/adopters.md
This pull request adds PITS Globale Datenrettungsdienste to the list of adopters
=> Add PITS Globale Datenrettungsdienste as an adopter

docs/en/integrations/language-clients/nodejs.md
* See https://github.com/ClickHouse/clickhouse-js/pull/167
* Rearranged methods in the doc (makes more sense now)
* Better "endless" streaming example
=> ClickHouse-JS 0.1.0 update

docusaurus.config.js
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1186
=> Add breadcrumbs to docs

docs/en/about-us/adopters.md
=> Adding Request Metrics

docs/en/integrations/language-clients/nodejs.md
Document new features introduced in https://github.com/ClickHouse/clickhouse-js/pull/169.
=> ClickHouse-JS 0.1.1 - Keep Alive docs

docs/en/cloud/security/aws-privatelink.md, docs/en/cloud/security/gcp-private-service-connect.md
Added Terraform code snippets for GCP Private service connect
closes https://github.com/ClickHouse/data-plane-application/issues/4858
=> GCP PSC: added terraform code

docusaurus.config.js
still working on double-slash issue
=> remove redir

knowledgebase/python_http_requests.md
This PR adds a new KB article showing use of Python sample code using requests module to read/write to Clickhouse
=> [KB] Python HTTP example

docs/en/about-us/adopters.md
Append KUJIALE about use CK in log system.
=> log: append adopter about use CK in log system

docs/en/integrations/data-ingestion/kafka/index.md
Update docs with 2 new types Time & Timestamp
=> Update supported types for ClickHouse Kafka Connect Sink

docs/en/about-us/adopters.md
The Turkcell Splunk Migration Project showcased ClickHouse's ability to handle massive data volumes effortlessly. With an infrastructure that consists of only 2 physical nodes, ClickHouse efficiently manages an incredible 2 terabytes of log data every single day.
=> Add Turkcell success story

docs/en/integrations/data-ingestion/kafka/index.md
as per discussion with the Confluent team
=> remove outdated comment. confluent support customer settings

docs/en/cloud/reference/changelog.md
=> Add cloud change log for July 27 2023

knowledgebase/how_to_use_parametrised_views.md
This KB adds a basic example showing use of parametrised views.
=> [KB] Example use of parametrised view

docs/en/guides/developer/alternative-query-languages.md
ref https://github.com/ClickHouse/ClickHouse/pull/53060
=> Update docs for prql 0.9

docs/en/cloud/reference/changelog.md
=> Update cloud changelog for Aug 24

docs/en/integrations/language-clients/java/index.md
Added an example demonstrating dedicated SSL configuration for connecting to ClickHouse using JDBC.
=> Add a dedicated SSL example

knowledgebase/terraform_example.md
This PR adds a KB article on how to use terraform to manage clusters using Cloud API.
=> [KB] terraform_example_kb_article

docs/en/integrations/data-ingestion/kafka/index.md
based on https://github.com/ClickHouse/clickhouse-kafka-connect/pull/176/
=> Kafka Connector: add docs for options, add recipes

knowledgebase/change-billing-email.md
This adds a new KB article on "How do I change my Billing Contact in ClickHouse Cloud?".
=> New KB Article: How do I change my Billing Contact in ClickHouse Cloud?

knowledgebase/check_users_roles.md
adds a KB on checking users assigned to roles and viceversa
=> [KB] check user roles kb

docs/en/about-us/adopters.md
Adding many adopters and cleaning up backlog
=> adding multiple adopters

docs/en/cloud/manage/service-types.md, sidebars.js
Support has requested a page to point to prospective customers describing the different service types in more detail
=> Create page summarizing service types

docs/en/cloud/reference/changelog.md
=> Update cloud changelog with Sept 28 changes

package.json
It ran `sh` with a script that uses bash features.
=> Fix prep-from-local

docs/en/cloud/security/compliance-and-certification.md, sidebars.js
@leticiawebb for review. @arisarose requested we have a cloud compliance page linking to our Trust Center in the docs
=> Add cloud compliance page

docs/en/integrations/language-clients/java/index.md
Documenting SSL feature on Java Client Release v0.5.0 [Latest](https://github.com/ClickHouse/clickhouse-java/releases/latest)
=> Java client - Add ssl key store properties

docs/en/about-us/support.md
This corrects a typo on the [Support page](https://clickhouse.com/docs/en/about-us/support).
=> Fix: Corrects typo

knowledgebase/about-quotas-and-query-complexity.md
KB About Quotas and Query complexity
=> [KB] About Quotas and Query complexity

sidebars.js
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1610
Added the **Cluster Discover** page to the sidebar underneath **Cluster Deployment**.
=> Adds 'Cluster Discovery' to the sidebar.

docs/en/integrations/sql-clients/sql-console.md, yarn.lock
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1594
=> Adds GenAI mini-guide to SQL Console.

docs/en/guides/sre/keeper/index.md
This command is being added https://github.com/ClickHouse/ClickHouse/pull/56354
=> Add docs for 4 letter command for yielding leadership in keeper cluster

docs/en/about-us/adopters.md
Issues taken from https://github.com/ClickHouse/clickhouse-docs/issues?q=is%3Aissue+is%3Aopen+Adopters
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1583 https://github.com/ClickHouse/clickhouse-docs/issues/1555 https://github.com/ClickHouse/clickhouse-docs/issues/1542 https://github.com/ClickHouse/clickhouse-docs/issues/1528 https://github.com/ClickHouse/clickhouse-docs/issues/1524 https://github.com/ClickHouse/clickhouse-docs/issues/1667
=> Adds adopters from issues listed in GH.

docs/en/cloud/security/gcp-private-service-connect.md, docs/en/guides/developer/cascading-materialized-views.md, docs/en/guides/sre/user-management/ssl-user-auth.md, docs/en/integrations/data-ingestion/data-formats/json.md
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1672
=> Adds mini-guide youtube videos.

knowledgebase/schema_migration_tools.md
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1582
=> Removes Atlas schema migration tool from list.

docs/index.md, docusaurus.config.js, sidebars.js
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1685
=> Hides Home link in sidebar.

docs/en/integrations/index.mdx
=> Updates anchor link to docs contributing.

knowledgebase/node-js-example.md
nodejs basic example using @clickhouse/client
=> [knowledgebase] nodejs basic example using @clickhouse/client

docs/en/cloud/reference/changelog.md
Reviews recent changes to the changelog that were pushed without a review in [73f59d4](https://github.com/ClickHouse/clickhouse-docs/commit/73f59d433db8ee57941fc147325d4bf09d426908).
=> Improves formatting. Clarifies uncertain statements.

yarn.lock
Replaces https://github.com/ClickHouse/clickhouse-docs/pull/1628 https://github.com/ClickHouse/clickhouse-docs/pull/1627 https://github.com/ClickHouse/clickhouse-docs/pull/1625
=> Upgrades, like, all the packages man.

docs/en/integrations/data-ingestion/kafka/msk/index.md
=> Add a section in the MSK setup to discuss internet access and private link setup

docs/en/about-us/adopters.md
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1708 https://github.com/ClickHouse/clickhouse-docs/issues/1707 https://github.com/ClickHouse/clickhouse-docs/issues/1706 https://github.com/ClickHouse/clickhouse-docs/issues/1554 https://github.com/ClickHouse/clickhouse-docs/issues/1528
=> Adds lots of new adopters.

docs/en/cloud/reference/shared-merge-tree.md
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1728
=> SharedMergeTree is now enabled by default.

docs/en/integrations/data-visualization/tableau-online-and-clickhouse.md
this is a bit buried and often gets missed
=> Tableau Online: Highlight SSL cert to download

docs/en/_snippets/_clickhouse_mysql_on_premise_setup.mdx
Add instruction for configuring `listen_host`
=> Update _clickhouse_mysql_on_premise_setup.mdx to include listen_host

docs/en/cloud/security/gcp-private-service-connect.md
Please do not merge, this should be deployed after enablement self-service private link feature
Part of https://github.com/ClickHouse/data-plane-application/issues/6885
=> Updated docs for GCP Private Service Connect

docs/en/cloud/security/aws-privatelink.md, docs/en/cloud/security/gcp-private-service-connect.md
Fixing incorrect API endpoints
Removed references to "Supported regions" table.
=> fixes for PL / PSC docs

docs/en/integrations/data-ingestion/clickpipes/index.md
=> Add us-east-1 clickpipes static ips and convert the list to a table separated by region

docusaurus.config.js
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1247
=> Fixes inbound 404ing links from Cloudflare.

docs/en/guides/sre/keeper/index.md
https://github.com/ClickHouse/ClickHouse/pull/55876
=> Add docs on Keeper HTTP control port

docs/en/cloud/security/gcp-private-service-connect.md
Reverts ClickHouse/clickhouse-docs#1748
There was a migration problem, Slack Thread: https://clickhouse-inc.slack.com/archives/C02ESBRLJD7/p1701996091587099
=> Revert "revert PSC docs"

docs/en/integrations/data-visualization/powerbi-and-clickhouse.md
Add documentation regarding ClickHouse/power-bi-clickhouse#5
=> Power BI service doc

docs/en/guides/sre/keeper/index.md
https://github.com/ClickHouse/ClickHouse/pull/55876
=> Revert "Revert "Add docs on Keeper HTTP control port""

docs/en/cloud/reference/changelog.md
Update cloud changelog.md - Dec 18 2023
=> Update cloud changelog.md - Dec 18 2023

docusaurus.config.js
Motivation: https://github.com/ClickHouse/ClickHouse/pull/57547
=> Update redirects for materialized views

docs/en/about-us/adopters.md
Adds new adopters and sorts list.
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1776
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1772
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1769
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1768
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1766
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1755
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1754
=> Adds a few new adopters.

docs/en/about-us/adopters.md
Closes [1787](https://github.com/ClickHouse/clickhouse-docs/issues/1787)
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1788.
=> Adds Lago and Vexo to adopters

docs/en/cloud/manage/scaling.md
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1784
=> Adds clarification for CPU and RAM reqs.

README.md
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1817
=> Clarifies issue creation and assignee steps.

src/css/home.scss, src/theme/DocItem/Layout/styles.module.css
Fixes https://github.com/ClickHouse/clickhouse-docs/issues/1780
=> Fixes ToC horizontal overflow issue.

docs/en/about-us/adopters.md
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1841
=> Adds ScrapingBee to Adopters list.

sidebars.js
Add page from https://github.com/ClickHouse/ClickHouse/pull/58810
=> Add `Allocation profiling` to sidebar

docs/en/integrations/language-clients/js.md
* Add an entry about the `additional_headers` setting
* Add a reverse proxy note
* Fix the Date*/DateTime* bit
* Fix some typos
=> Update CHJS docs as of 0.2.9

docs/en/concepts/olap.md
Made some minor grammar edits and changes to olap.md. I have tried to keep the text as close as possible to the original, only making grammar edits or making changes which feel to me as an English native speaker to make the text easier to flow.
=> grammar edit of olap.md 

docs/en/guides/sre/keeper/index.md
Add the `can_become_leader` parameter
=> Describe how to set up a learner in Keeper

docs/en/cloud/security/aws-privatelink.md
Duplicate of closed PR: https://github.com/ClickHouse/clickhouse-docs/pull/1874/files
=> Updates JQ command in privatelink docs.

docs/en/guides/sre/user-management/index.md
Add link to cloud console users
=> Add link to cloud console users

docs/en/integrations/language-clients/js.md
See https://github.com/ClickHouse/clickhouse-js/pull/227
=> Update status of support for Nested data type by JavaScript client

knowledgebase/backing_up_a_specific_partition.md, knowledgebase/backup_specific_partition.md
backup individual partition in clickhouse oss
=> [Kb] backup individual partition in clickhouse oss

knowledgebase/read_consistency.md
Adds a KB to document how to achieve read consistency
=> [KB] read consistency

docs/en/concepts/glossary.md
Closes https://github.com/ClickHouse/clickhouse-docs/issues/2054
=> Adds CMEK to glossary.

docs/en/about-us/adopters.md
Closes https://github.com/ClickHouse/clickhouse-docs/issues/2093
=> Adds SiteBehaviour Analytics to adopters.

docs/en/integrations/data-visualization/powerbi-and-clickhouse.md
Change the connector path to the right location after MS's clarification at MicrosoftDocs/powerbi-docs#4907
=> Power BI - Fix connector path

docs/en/integrations/language-clients/java/index.md
Adds various minor language improvements to the Java client page.
=> docs: add various edits to Java client page

docs/en/integrations/language-clients/python/index.md
Update for minor changes from v0.5.24 to v0.7.3
=> Refresh ClickHouse Connect docs

docs/en/integrations/language-clients/python/index.md
Adds a reference to the new 0.7.4 `query_arrow_stream` method.
=> Python arrow stream

docs/en/guides/sre/keeper/index.md
for this PR https://github.com/ClickHouse/ClickHouse/pull/59516
=> add doc for cgroups_memory_observer_wait_time

docs/en/integrations/data-visualization/powerbi-and-clickhouse.md
per customer feeback:
update path for power BI:
from 
```
Create the following directory for the custom connector "[Documents]\Power BI Desktop\Custom Connectors directory"
```
to
```
Create the following directory for the custom connector "[Documents]\Power BI Desktop\Custom Connectors" directory
```
=> Update  power bi path - move quotes

package.json, yarn.lock
Reverts ClickHouse/clickhouse-docs#2182
=> Revert "Bump esbuild-loader from 4.0.3 to 4.1.0"

package.json, yarn.lock
Reverts ClickHouse/clickhouse-docs#2180
=> Revert "Bump @docusaurus/module-type-aliases from 3.1.1 to 3.2.0"

docs/en/integrations/language-clients/python/index.md
This incorporates recent minor Python updates
=> Minor Python update for recent releases

docs/en/cloud/reference/supported-regions.md
To be merged when Tokyo AWS region is enabled
=> Add Tokyo as supported AWS region

docs/en/guides/developer/ttl.md
closes: https://github.com/ClickHouse/ClickHouse/issues/62683
=> fix incorrect example of column TTL

docs/en/integrations/language-clients/python/index.md
Related: https://github.com/ClickHouse/ClickHouse/issues/62630
=> Add clickhouse-connect file streaming example

docs/en/integrations/data-ingestion/clickpipes/index.md
Add more explicit examples for configuring the ClickPipes schema registry url
=> Improve ClickPipes schema registry docs

docs/en/integrations/data-ingestion/dbms/mysql/index.md
Just a single word spelling fix.
=> Fix minor spelling mistake in MySQL docs

docs/en/cloud/manage/backups.md, docs/en/cloud/marketplace.md, docs/en/cloud/security/aws-privatelink.md, docs/en/cloud/security/cloud-endpoints-api.md, docs/en/cloud/security/secure-s3.md, docs/en/cloud/security/users-and-roles.md
Fix multiple typos under docs/en/cloud, changes as in PR.
=> Fix multiple typos under docs/en/cloud

docs/en/integrations/data-ingestion/clickpipes/index.md
Adds a few new virtual columns (soon to be supported in prod).
=> More ClickPipes virtual columns

docs/en/integrations/data-ingestion/clickpipes/index.md
https://clickhouse-inc.slack.com/archives/C03A9B0H05T/p1714745825524999
=> Remove "Coming soon" from Kafka streaming TSV support

.github/workflows/pull-request.yml, docs/en/guides/sre/keeper/index.md
Improve the keeper guide, follow-up for https://github.com/ClickHouse/ClickHouse/issues/62505
=> Add a documentation on how to extend a single-node keeper

docs/en/integrations/data-ingestion/dbms/mysql/index.md
https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin
https://dev.mysql.com/doc/refman/8.0/en/replication-options-gtids.html#sysvar_gtid_mode
https://dev.mysql.com/doc/refman/8.0/en/replication-options-gtids.html#sysvar_enforce_gtid_consistency
=> Fix mysql configurations typo

docs/en/guides/developer/cascading-materialized-views.md
`year_aggregated_data` ---> `year_aggregated_data_mv`
=> fix the error in cascading-materialized-views.md

docs/en/cloud/reference/cloud-compatibility.md
closes https://github.com/ClickHouse/clickhouse-docs/issues/2352
=> add a note about unsupported formats on ClickHouse cloud 

docs/en/integrations/language-clients/js.md
Added the docs about the HTTP agent override.
=> Update the CHJS docs for 1.2.0

docs/en/_snippets/_clickhouse_mysql_cloud_setup.mdx
- "When not sure whether a tool supports TLS SNI, it is better to follow" -> "We highly recommend";
- Add a troubleshooting entry regarding username format
=> Update the MySQL docs regarding multiple users

knowledgebase/tips-tricks-optimizing-basic-data-types-in-clickhouse.md
This pull request provides tips and tricks for optimizing basic data types in ClickHouse
=> KB tips and tricks for optimizing basic data types in CH

docs/en/whats-new/changelog/2023.md
=> Update 2023.md should delete = signal

docs/en/integrations/language-clients/python/index.md
See https://github.com/ClickHouse/clickhouse-connect/pull/375
=> Add the AsyncWrapper entry to the ClickHouse Connect docs.

knowledgebase/tips-tricks-optimizing-basic-data-types-in-clickhouse.md
Knowledge base to provide tips and tricks to optimize basic datatypes for speed and storage.
=> kb to provide tips/tricks to optimize basic datatypes

docs/en/guides/developer/alternative-query-languages.md
=> Fix typo in Alternative Query Language kusto doc link

docs/en/about-us/adopters.md
Adding a talk from Solarwinds at Innovate Summit 2017.
=> Update Solarwinds to adopters.md

docs/en/about-us/adopters.md
This is a new line item in adopters, adding Nutanix in the list.
=> Update Nutanix in adopters.md

plugins/menuItems.json, src/theme/Navbar/Content/GlobalMenu/index.js, src/theme/Navbar/Content/GlobalMenu/styles.module.css, src/theme/Navbar/Content/index.js
Updated menu order and added use cases. This is interim whilst we develop the new menu.
=> interim menu update

docs/en/integrations/data-ingestion/clickpipes/object-storage.md
Update scaling section, and add new materialized view notes.
=> Update object storage clickpipes docs

docs/en/integrations/prometheus.md
Fix invalid URLs in Prometheus Integration documentation.
=> Fix URL in Prometheus Integration docs

docs/en/integrations/language-clients/python/index.md
Tiny addition of a new clickhouse-connect global setting.
=> Add new global parameter to clickhouse-connect docs

docs/en/integrations/data-ingestion/clickpipes/kinesis.md, docs/en/integrations/data-ingestion/clickpipes/secure-kinesis.md
This adds a small blurb describing Kinesis Enhanced fan out support, links to AWS's documentation for the feature, and updates permissions to reflect these new enhanced fan out requirements.
=> Add blurb about enhanced fanout for kinesis and update permissions to reflect the new requirements

docs/en/use-cases/observability/managing-data.md, docs/en/use-cases/observability/schema-design.md
Hey! Just a tiny PR to remove some duplicate paragraphs :slightly_smiling_face:
=> Remove duplicate paragraph

docs/en/integrations/data-ingestion/clickpipes/object-storage.md
Lets make it more clear what needs to happen and what the consequences are.
=> Clarify limitations around DDL changes on Object storage Clickpipes

docs/en/guides/developer/ttl.md
Added an example demonstrating how to remove rows based on a field value.
=> TTL Example: Removing Rows Using Where Condition

docs/en/integrations/images/logos/goldsky.svg, docs/en/integrations/index.mdx
With the upcoming announcement on Wednesday of the ClickHouse CryptoHouse project in partnership with Goldsky, we'd like to get our name and logo up on this page before that if possible. Please let me know if I need to make any additional changes besides what's in this request.
=> Goldsky Partner Addition

.github/pull_request_template.md
we can add other things to the checklist later
=> add a pr template with a checklist

knowledgebase/mapping-of-system-metrics-to-prometheus-metrics.md
=> Add back missing KB article

sidebars.js
Add Deduplicating Inserts on Retries to sidebar
=> Add Deduplicating Inserts on Retries to sidebar

docs/en/integrations/data-ingestion/apache-spark/index.md
Update package to `com.clickhouse.spark` and relevant urls
=> Update package to com.clickhouse.spark and relevant urls

docs/en/integrations/language-clients/go/index.md
Object('JSON') type is depreacated: https://clickhouse.com/docs/en/sql-reference/data-types/object-data-type
A new JSON type will replace it in a future: https://clickhouse.com/docs/en/sql-reference/data-types/newjson
Until then, we remove all old type use case mentions. Related to https://github.com/ClickHouse/clickhouse-go/pull/1377.
=> Remove Object('JSON') type usage examples from clickhouse-go documentation

docs/en/integrations/data-ingestion/clickpipes/kafka.md, docs/en/integrations/data-ingestion/clickpipes/kinesis.md
Adds details around performance for Kinesis and Kafka ClickPipes
Closes https://github.com/ClickHouse/clickpipes-platform/issues/2617
=> Add details for ClickPipes performance

docs/en/integrations/data-ingestion/apache-spark/index.md
Fix headings so they're displayed correctly in the navigation and the in-page link works. Plus some light editing.
=> Spark: Fix headings

docs/en/chdb/guides/querying-pandas.md
=> querying pandas

sidebars.js
This page is not attached anywhere: https://clickhouse.com/docs/en/interfaces/prometheus
=> Add new Prometheus page to sidebar

docs/en/about-us/adopters.md
Added Backpack Exchange as a line item in adopters
=> Update adopters.md with Backpack Exchange meetup resources

docs/en/integrations/data-ingestion/clickpipes/secure-kinesis.md
Update permission list for clickpipes for kinesis
=> Update kinesis permissions needed for clickpipes

sidebars.js
=> Add Pandas guide to sidebar

docs/en/cloud/security/common-access-management-queries.md
Same as https://github.com/ClickHouse/clickhouse-docs/pull/2576
=> Fix SQL console role spelling

docs/en/guides/best-practices/skipping-indexes.md
=> remove typo

docs/en/integrations/data-visualization/grafana/config.md
Corrected the incorrect YAML config keys for the grafana plugin
=> grafana plugin: fix incorrectly named YAML config keys

docs/en/concepts/why-clickhouse-is-so-fast.md
=> VLDB paper

docs/en/integrations/data-ingestion/etl-tools/apache-beam/README.md
The JDBC driver has been updated in the head version, waiting for the release
=> Beam connector: remove unrelevant limitations

docs/en/chdb/guides/querying-apache-arrow.md, sidebars.js
=> apache arrow guide

docs/en/integrations/data-ingestion/clickpipes/kafka.md, docs/en/integrations/data-ingestion/clickpipes/kinesis.md
Update ClickPipes supported data types and document new _raw_message virtual column
=> ClickPipes doc update including _raw_message virtual column

docs/en/about-us/adopters.md
AMP and SwarmFarm Robotics engineers presented at the Melbourne meetup on September 27. I added their meetup slides in adopters.  AMP was already an existing adopter so just added 1 more resource in the same line.
=> Update adopters.md with AMP and SwarmFarm Robotics meetup slides

docs/en/integrations/data-ingestion/etl-tools/apache-beam.md, sidebars.js
=> Add Apache Beam to sidebar

docs/en/chdb/index.md, docs/en/chdb/install/bun.md, docs/en/chdb/install/c.md, docs/en/chdb/install/go.md, docs/en/chdb/install/nodejs.md, docs/en/chdb/install/python.md, docs/en/chdb/install/rust.md
=> chDB home page

docs/en/integrations/language-clients/python/index.md
Updates for the 0.8.0 clickhouse-connect release, including experimental JSON datatype support.
=> clickhouse-connect update for 0.8.0 beta release

docs/en/integrations/data-ingestion/clickpipes/kafka.md
Updates the FAQs to add frequently addressed comments regarding Azure Event Hubs.
=> [ClickPipes] Enhance Azure Event Hubs FAQs

docs/en/cloud/security/compliance-overview.md, docs/en/cloud/security/shared-responsibility-model.md
Added HIPAA to our compliance page and updated the shared responsibility model to include BYOC.
=> HIPAA launch docs

sidebars.js
Add sidebar for Confluent HTTP sink connector
=> Add sidebar for Confluent HTTP sink connector

docusaurus.config.js, sidebars.js
It is confusing, and I was not able to find what is `E111 | Single row SELECT statement`.
This is from the official standard document that is difficult to find and use.
=> Remove ANSI from sidebar

docs/en/cloud/security/cloud-access-management.md, docs/en/cloud/security/cloud-authentication.md
- Added MFA self-service recovery codes
- Added account recovery methods
- Updated flow and MFA to show MFA applies to email + password and social auth
- Added a reference to SAML SSO
=> MFA Updates

docs/en/about-us/distinctive-features.md
=> Remove broken link

docs/en/integrations/language-clients/java/client-v2.md
Improving the readability of the client v2 page
=> Update client-v2 docs

docs/en/cloud/manage/billing.md
updated billing FAQs to include details around prepaid credits usage
=> Update billing.md to include details around prepaid credits usage

src/theme/Navbar/Content/index.js, src/theme/Navbar/Content/styles.module.css
=> Fix top nav bar CSS

knowledgebase/search-across-node-for-tables-with-a-wildcard.md
=> Update search-across-node-for-tables-with-a-wildcard.md with EXCEPT 

sidebars.js
Change "Example datasets" to title case
=> Change "Example datasets" to title case

package.json
=> Temp disable settings build

scripts/settings/autogenerate-settings.sh
=> Fix parsing of settings after recent refactor

docs/en/migrations/postgres/replacing-merge-tree.md
=> note on max_bytes_to_merge_at_max_space_in_pool

docs/en/integrations/data-ingestion/etl-tools/dbt/index.md
Add an indication for the new Fivetran Transformation feature over `dbt-clickhouse`
=> add dbt fivetran support

docs/en/integrations/data-ingestion/clickpipes/kafka.md, docs/en/integrations/data-ingestion/clickpipes/kinesis.md
Mention the scaling controls and update the default value.
=> Update streaming clickpipes scaling docs

sidebars.js, src/theme/Navbar/Content/index.js
=> Sidebar link changes

src/components/DocsCategoryDropdown/index.jsx, src/components/DocsCategoryDropdown/styles.module.css, src/theme/Navbar/Content/index.js
Add Knowledge Base link to navbar
=> Add Knowledge Base link to navbar

docs/en/use-cases/observability/schema-design.md
=> fix levels for observability guide

sidebars.js, src/theme/Navbar/Content/index.js
=> Add missing sidebar links

src/theme/Navbar/Content/index.js
Adding a comment to help understand how to configure a link in the top nav bar.
=> Adding a comment to help understand how to configure a link in the top nav bar

docs/en/migrations/postgres/replacing-merge-tree.md
Better docs for RMT
@cwurm @antonio2368 please
=> document merge behavior for RMT

docs/en/integrations/language-clients/java/index.md
removed commitment based on the discussions in https://github.com/ClickHouse/clickhouse-java/issues/1870 and https://github.com/ClickHouse/clickhouse-js/issues/172
=> remove commitment to failover and load-balancing

knowledgebase/how-to-set-up-ch-on-docker-odbc-connect-mssql.md
Update link to use official Docker image
=> Update Docker link

docs/en/cloud/manage/sticky-endpoints.md, sidebars.js
=> Add Sticky Endpoints doc

docs/en/cloud/reference/supported-regions.md, src/css/custom.scss
Change heading styles for h3 and h4
=> Change heading styles for h3 and h4

src/theme/DocSidebar/Desktop/index.js
Remove left nav animation on navigate
=> Remove left nav animation on navigate

docs/en/materialized-view/refreshable-materialized-view.md
Add APPEND section for refreshable materialized views
=> Add APPEND section for refreshable materialized views

knowledgebase/profiling-clickhouse-with-llvm-xray.md
Minor improvement for Profiling with XRay
=> Minor improvement for Profiling with XRay

docs/en/cloud/reference/supported-regions.md
=> Remove unnecessary headings

docs/en/cloud/reference/changelog.md
Add title to customer notifs changelog entry
=> Add title to customer notifs changelog entry

src/theme/Navbar/Content/styles.module.css
=> Do what I want

src/css/home.scss
=> Do what I want, part 2

docs/en/cloud/security/cloud-access-management.md
Adding the Cloud Billing role definition to the user access documentation
=> Add Cloud Billing role

knowledgebase/exchangeStatementToSwitchTables.md
A knowledge base article to show an example of using the EXCHANGE command to switch tables.
=> KB to show an example of using EXCHANGE command to switch tables

docs/en/guides/inserting-data.md
=> minor fix to insert docs

docs/en/use-cases/observability/managing-data.md
Closes https://github.com/ClickHouse/docs-private/issues/221
=> cross link ttl_only_drop_parts

docs/en/materialized-view/index.md
=> Doc about MV and filter/JOIN

docs/en/cloud/security/saml-sso-setup.md
=> fix htmltest test failure

docs/en/integrations/data-ingestion/clickpipes/postgres/index.md
=> feat: add IP whitelisting nudge

docs/en/materialized-view/index.md
=> Followup for #2827

docs/en/cloud/manage/dashboards.md
=> updates by Mihir

sidebars.js
=> Add new warehouse page to side bar

docs/en/integrations/data-ingestion/clickpipes/kafka.md
Adds information on how to connect ClickPipes to MSK using IAM auth
=> [ClickPipes] Add information on MSK IAM

docs/en/integrations/data-ingestion/clickpipes/kafka.md
=> Add beta note to iam auth for clickpipes

docs/en/about-us/adopters.md
Adding Talo to the list of adopters
=> Add Talo to adopters

docs/en/about-us/adopters.md
Add Alauda to adopters
We use Clickhouse and want to add our company to the adopters
=> Add Alauda to adopters

docs/en/about-us/adopters.md
=> Add WebScrapingHQ to adopters.md

docs/en/use-cases/observability/grafana.md
Closes https://github.com/ClickHouse/clickhouse-docs/issues/2748
Increase size of images and make them open in new window
=> increase image sizes for grafana

docs/en/about-us/adopters.md
=> more adopters

docs/en/guides/inserting-data.md
Closes https://github.com/ClickHouse/clickhouse-docs/issues/2647
=> improve language

docs/en/materialized-view/index.md
Note per https://github.com/ClickHouse/clickhouse-docs/issues/2571
=> add note on GROUP BY = ORDER BY

docs/en/integrations/language-clients/go/index.md
https://github.com/ClickHouse/clickhouse-docs/issues/2296
=> clarify uncompressed

docusaurus.config.js
https://github.com/ClickHouse/clickhouse-docs/pull/new/issue_2428
=> re-direct for replication

docs/en/integrations/data-visualization/grafana/config.md
=> fix grafana config

docs/en/intro.md, src/css/colors.scss
Lighten border per https://github.com/ClickHouse/clickhouse-docs/issues/2209
**Old:**
**New:**
=> lighten border for dark mode

docs/en/cloud/manage/billing.md, docs/en/cloud/manage/billing/marketplace/index.md
https://github.com/ClickHouse/clickhouse-docs/issues/2600
=> add faq on marketplace vs cloud

docs/en/get-started/cloud-quick-start.md, docs/en/guides/inserting-data.md, docs/en/integrations/data-ingestion/insert-local-files.md, docs/en/integrations/language-clients/java/jdbc-driver.md, docs/en/migrations/bigquery/loading-data.md, docs/index.md, sidebars.js, src/theme/Navbar/Content/index.js
Reogs all integrations to a structure agreed with @Ryado
=> reorg all integrations

knowledgebase/why_is_my_primary_key_not_used.md
https://github.com/ClickHouse/clickhouse-docs/issues/900
=> note on read_in_order in KB

src/theme/DocItem/Footer/index.js, src/theme/DocItem/Footer/styles.module.css, src/theme/DocItem/Layout/index.js, src/theme/DocItem/Layout/styles.module.css
=> move edit this page to top

src/theme/DocSidebar/Desktop/index.js
Fixes https://github.com/ClickHouse/clickhouse-docs/issues/2869
cc @rfraposa
=> fix scroll to parent

docs/en/cloud/security/aws-privatelink.md, docs/en/cloud/security/gcp-private-service-connect.md
Notes about corss-region connectivity in AWS/GCP
=> [AWS PL/GCP PSC] cross-region notes

docs/en/integrations/data-ingestion/data-formats/json/intro.md
=> new JSON type

knowledgebase/how-to-filter-a-clickhouse-table-by-an-array-column.md, knowledgebase/how-to-insert-all-rows-from-another-table.md
PR to close https://github.com/ClickHouse/clickhouse-docs/issues/1715 and https://github.com/ClickHouse/clickhouse-docs/issues/1714
=> add kb articles on filtering using array-columns and ingest all rows 

knowledgebase/comparing-metrics-between-queries.md
Improve query - thanks to @nikita-vanyasin
=> improve query comparison query

knowledgebase/add-column.md
=> knowledge base: add column

docs/en/cloud/security/aws-privatelink.md
=> [AWS] Update for "Multiple PrivateLinks in one region"

plugins/header.js, src/theme/Navbar/Content/index.js
=> fix stars?

docusaurus.config.js, plugins/header.js, src/theme/Navbar/Content/index.js
=> restore github stars

docs/en/tutorial.md
Remove parts reference from the tutorial, as that concept is not yet required.
=> Remove parts reference from tutorial

docs/en/integrations/language-clients/java/client-v1.md, docs/en/integrations/language-clients/java/client-v2.md, docs/en/integrations/language-clients/java/jdbc-driver.md
- configuration documentation update
- deprecation warning for client-v1
Closes https://github.com/ClickHouse/clickhouse-java/issues/1884
Closes https://github.com/ClickHouse/clickhouse-java/issues/1950
Closes
=> [java-client] doc updates for configuration

docs/en/integrations/data-visualization/quicksight-and-clickhouse.md, docs/en/integrations/sql-clients/sql-console.md
=> final experimental badges

knowledgebase/schema_migration_tools.md
Hey folks, we [open-sourced](https://www.june.so/blog/houseplant-database-migrations-for-clickhouse) the tool we use at @juneHQ to manage our clickhouse schema. Would love to add it to this list of migration tools in the clickhouse docs.
=> Add Houseplant

docs/en/_snippets/_self_managed_only_automated.md, docs/en/_snippets/_self_managed_only_no_roadmap.md, docs/en/_snippets/_self_managed_only_not_applicable.md, docs/en/_snippets/_self_managed_only_roadmap.md, docs/en/cloud/manage/backups.md, docs/en/guides/developer/ttl.md, docs/en/integrations/data-ingestion/data-formats/binary.md, docs/en/integrations/data-ingestion/dbms/dynamodb/index.md, docs/en/integrations/data-ingestion/kafka/kafka-table-engine.md, docs/en/integrations/language-clients/js.md, docs/en/integrations/sql-clients/sql-console.md, src/theme/badges/PrivatePreviewBadge/index.js, src/theme/badges/PrivatePreviewBadge/styles.module.css
Final tag for private preview + tag features
=> tags for cloud supported + private preview

src/theme/badges/PrivatePreviewBadge/styles.module.css
=> fix style for private preview

docs/en/about-us/distinctive-features.md
=> Add link to SAMPLE in distinctive-features.md

docs/en/about-us/adopters.md
=> Update adopters.md with Electrum blog and remove Backpack

docs/en/integrations/data-ingestion/clickpipes/postgres/faq.md, docs/en/integrations/data-ingestion/clickpipes/postgres/schema-changes.md
- also added schema changes page here
=> [clickpipes] Add more FAQs for Clickpipes for Postgres

docs/en/guides/developer/alternative-query-languages.md
Corresponding change in the main repository: https://github.com/ClickHouse/ClickHouse/pull/74224
Please merge only after the other PR is in.
=> Docs: Mark KQL and PRQL as experimental

docs/en/cloud/bestpractices/partitioningkey.md, docs/en/cloud/security/cloud-authentication.md, docs/en/cloud/security/gcp-private-service-connect.md
Fixes the broken hashes list from [#3039](https://github.com/ClickHouse/clickhouse-docs/issues/3039) for pages here on the docs repo.
=> update broken hashes for cloud

docs/en/guides/developer/lightweight-update.md
Update light weight updates to use the available in Cloud badge.
=> Update lightweight updates with cloud badge

docs/en/integrations/data-ingestion/s3/performance.md
Fixes remaining broken link on page:
https://clickhouse.com/docs/en/integrations/s3/performance
=> fix broken link

docs/en/integrations/data-ingestion/clickpipes/postgres/index.md
=> feat(clickpipes): add warning that pg proxies are not supported for CDC

knowledgebase/why_default_logging_verbose.md
Close https://github.com/ClickHouse/clickhouse-docs/issues/2726
=> add kb on default logging level

docs/en/quick-start.mdx
Corresponding PR in code repo: https://github.com/ClickHouse/ClickHouse/pull/74522
=> Docs: Point to KB article about verification errors

package.json, yarn.lock
=> upgrade express to 4.21.0

knowledgebase/why_default_logging_verbose.md, package.json, yarn.lock
=> Upgrade ws

package.json, yarn.lock
=> express update

src/css/custom.scss
Fix for incorrect sidebar behaviour on firefox.
=> Fix sidebar behaviour on firefox

knowledgebase/profiling-clickhouse-with-llvm-xray.md
=> Fix missing end quotes

docs/en/about-us/adopters.md
Update the adopters knowledge URL for Phare.io
=> Update adopters knowledge link for Phare.io

scripts/settings/autogenerate-settings.sh
Closes https://github.com/ClickHouse/clickhouse-docs/issues/3088
=> Remove string replacement from autogenerate settings script

src/css/custom.scss
=> Fix styling for docusaurus dropdown modal

docs/en/faq/general/ne-tormozit.md
=> Fix video size on page "не тормозит"

docs/en/about-us/history.md
=> Fix grammar

src/css/custom.scss, src/theme/BlogListPage/StructuredData/index.js, src/theme/BlogListPage/index.js, src/theme/BlogPostItem/Container/index.js, src/theme/BlogPostItem/Content/index.js, src/theme/BlogPostItem/Footer/ReadMoreLink/index.js, src/theme/BlogPostItem/Footer/index.js, src/theme/BlogPostItem/Header/Authors/index.js, src/theme/BlogPostItem/Header/Authors/styles.module.css, src/theme/BlogPostItem/Header/Info/index.js, src/theme/BlogPostItem/Header/Info/styles.module.css, src/theme/BlogPostItem/Header/Title/index.js, src/theme/BlogPostItem/Header/Title/styles.module.css, src/theme/BlogPostItem/Header/index.js, src/theme/BlogPostItem/index.js
- make all text 14px
- Title: font-weight: 600
- description + date: font-weight: 400
- change the order to:
- title
- description
- date
- badge
- use a muted color for the date
- change date format to : Mon DD, YYYY, e.g.: Jan 27, 2025
- use one of our badges
Additionally:
- improves styling of tags pages
=> KB page: update styling of KB page

docs/en/integrations/prometheus.md
Update docs to reflect new prometheus capabilities
=> Add filtered metrics request param to prom endpoint

docs/en/integrations/prometheus.md
=> Fixing broken table links

knowledgebase/read_consistency.mdx
Minor patches as I was reading through the page.
=> knowledgebase: update read_consistency.mdx

docs/en/cloud/reference/byoc.md
=> Cleanup byoc

docs/en/cloud/bestpractices/usagelimits.md
=> Update usagelimits.md with list from SA team

src/theme/Navbar/Content/index.js
=> Fix top level menus

docs/en/cloud/reference/byoc.md
=> [BYOC]Small fix for VPC peering guide

.github/workflows/build-search.yml
=> fix action

docs/en/cloud/reference/warehouses.md
Adding docs note about ability to create users on Hydra RO services.
=> Kapustor patch 1

docusaurus.config.js, src/theme/Navbar/Content/index.js
=> language selector

knowledgebase/aws-privatelink-setup-for-clickpipes.mdx
=> chore(minor): remove orphan link

docs/en/cloud/reference/supported-regions.md, docs/en/cloud/security/compliance-overview.md, docs/en/cloud/security/shared-responsibility-model.md
Add PCI to our compliance overview and shared responsibility model pages, and update the list of compliant regions.
=> PCI Update

docs/en/integrations/language-clients/java/index.md
* Gave an example of dependency and configuration (while detailing some other options)
Closes https://github.com/ClickHouse/clickhouse-java/issues/2003
=> Adding logging details to the java docs

docs/en/guides/developer/understanding-query-execution-with-the-analyzer.md, docs/en/guides/sre/keeper/index.md, docs/en/managing-data/core-concepts/partitions.md, docs/en/use-cases/observability/introduction.md
Fixes the remaining code blocks without a language that I missed previously.
=> fix more code blocks

docs/en/concepts/why-clickhouse-is-so-fast.md
First 4 Why is ClickHouse fast? videos
=> first 4 videos

docs/en/cloud/reference/byoc.md
Update BYOC feature list as the project evolves
=> Update BYOC feature list

docs/en/integrations/data-ingestion/clickpipes/postgres/index.md
- Swaps Private Preview badge for Beta Badge
=> CDC: beta badge

README.md
=> Test PR (CODEOWNERS) - Add Alt Text

docs/en/integrations/data-ingestion/clickpipes/postgres/faq.md
=> feat(clickpipes): add docs for invalid snapshot identifier

docs/en/guides/sre/user-management/index.md
=> fix links to non-existent sections

docusaurus.config.js
temp while we deal with doc move
=> disable link checker

scripts/settings/autogenerate-settings.sh
=> remove sed

vercel.json
=> docs/en -> docs/

docusaurus.config.js, package.json, yarn.lock
Adding for issue detection e.g. 404
=> vercel analytics

package.json, vercel.json
=> More redirects

docs/cloud/reference/changelog.md
- Adds Cloud change log for 21 February 2025.
=> Changelog: add cloud change log 21 Feb 2025

vercel.json
=> redirects for 404s

docs/about-us/adopters.md
Added Last9 as an adopter with the meetup video from the Mumbai meetup
=> Update adopters.md with Last9 meetup video

docs/cloud/security/cloud-endpoints-api.md
Remove table of static IPs
More details at: https://clickhouse-inc.slack.com/archives/C03A9B0H05T/p1740420971546869
=> Remove table of static IPs

docs/cloud/reference/byoc.md, docs/cloud/reference/index.md, docs/cloud/reference/shared-merge-tree.md, docs/cloud/reference/warehouses.md, scripts/aspell-dict-file.txt, scripts/aspell-ignore/en/aspell-dict.txt, scripts/check-doc-aspell
Fix spellcheck which was broken during rename.
=> fix spellcheck

vercel.json
=> Fix more 404s

scripts/translate/translate.py
Handles translation of any language. Docs + ja content pending.
=> fix translation script

docs/cloud/manage/network-data-transfer.mdx
Long-term performance improvements on the ClickHouse side are tracked here: https://github.com/ClickHouse/ClickHouse/issues/75719.
=> Add clarity around edge cases where an INSERT can cause egress data transfer pricing

docs/integrations/data-visualization/powerbi-and-clickhouse.md
=> Fix rendering of note admonition

contribute/style-guide.md, docs/managing-data/core-concepts/academic_overview.mdx
In the academic_overview we have some links to spans such as:
```
<span id="page-2-0"></span><img src={image_02}/>
As shown by [Figure 2,](#page-2-0)...
```
This is a completely valid way of doing it and works when the docs are built,
but sadly docusaurus' anchor checker throws errors on this. At the moment 
they are just warnings but we want to turn the link checker on so in future 
the build will fail on these:
```
- Broken anchor on source page path = /docs/academic_overview:
-> linking to #page-1-0 (resolved as: /docs/academic_overview#page-1-0)
-> linking to #page-2-0 (resolved as: /docs/academic_overview#page-2-0)
-> linking to #page-6-0 (resolved as: /docs/academic_overview#page-6-0)
-> linking to #page-1-1 (resolved as: /docs/academic_overview#page-1-1)
-> linking to #page-9-0 …
```
=> Fix links to spans in academic_overview

docs/managing-data/updating-data/overview.md, docs/use-cases/observability/schema-design.md
- fixes two more broken anchors in docs
=> fix broken anchors

vercel.json
Adds new hits reported by HyperDX alert
=> Add more 404s to redirect list

docusaurus.config.jp.js, src/components/DocsCategoryDropdown/index.jsx
=> move jp to /docs

docusaurus.config.jp.js, i18n/jp/code.json, src/components/DocsCategoryDropdown/index.jsx
vercel not working with jp/docs
=> try jp-docs for jp docs in vercel

docusaurus.config.jp.js, i18n/jp/code.json, src/theme/BlogListPage/index.js, src/theme/BlogTagsListPage/index.js, src/theme/Navbar/Content/index.js
Translate top menu and move to /docs/jp
=> Translate improvements

docs/integrations/language-clients/java/client.md, docs/integrations/language-clients/java/jdbc.md
it shouldn't be a manual process, but it's a quick fix
=> bump java to 0.8.2

docs/guides/developer/debugging-memory-issues.md
=> Fix heading levels

i18n/jp/docusaurus-plugin-content-docs/current/cloud/security/accessing-s3-data-securely.md, i18n/jp/docusaurus-plugin-content-docs/current/integrations/data-ingestion/clickpipes/secure-kinesis.md
=> change jpg to png

docs/cloud/security/cmek.md
#3433 
- Update the enhanced encryption page with the procedure for key rotation.
- Consolidate duplicate warnings to the call-out at the top of the page.
- Create collapse sections for AWS/ GCP CMEK to make the page more readable
=> Add key rotation procedures and better organize sections

docusaurus.config.en.js, docusaurus.config.jp.js, docusaurus.config.ru.js, docusaurus.config.zh.js
=> Translations followup: all languages in locales

.github/ISSUE_TEMPLATE/translation_issue.yaml
Adds a github issue form for translations
=> Translations: add issue form for translations

docs/integrations/data-ingestion/dbms/postgresql/data-type-mappings.md
Add FixedString to PostgreSQL mapping
This should be merged only after https://github.com/ClickHouse/ClickHouse/pull/77304
=> Add FixedString to PostgreSQL mapping

vercel.json
=> en redirect should be fallback

contribute/style-guide.md
Style guide is not rendering correctly
=> Fix style guide rendering

package.json, yarn.lock
=> axios update

docs/cloud/reference/architecture.md, i18n/jp/docusaurus-plugin-content-docs/current/cloud/reference/architecture.md, i18n/ru/docusaurus-plugin-content-docs/current/cloud/reference/architecture.md, i18n/zh/docusaurus-plugin-content-docs/current/cloud/reference/architecture.md
Insanely svg elements must start upper case
=> fix arch image

src/theme/CodeBlock/index.js, src/theme/CodeBlock/styles.module.css
Fixes bug reported in https://github.com/ClickHouse/clickhouse-docs/issues/3277
=> Bug fix: fix scrolling which is not smooth

scripts/autogenerate-table-of-contents.sh
=> autogenerate table of contents for about/development

docs/cloud/manage/jan2025_faq/dimensions.md
=> Fix spacing

plugins/floating-pages-exceptions.txt
See discussion here: 
https://github.com/ClickHouse/ClickHouse/pull/77743#issuecomment-2737491913
=> Add page from main repo to exceptions

contribute/style-guide.md
=> Update Image style guide

docs/cloud/reference/shared-merge-tree.md, docs/guides/sre/keeper/index.md, docs/integrations/data-ingestion/data-formats/json/inference.md, docs/integrations/data-ingestion/etl-tools/dbt/index.md, docs/integrations/data-ingestion/s3/index.md, docs/use-cases/observability/integrating-opentelemetry.md, docs/use-cases/observability/managing-data.md
Remove `SETTINGS index_granularity = 8192`
https://github.com/ClickHouse/clickhouse-docs/issues/3089
=> remove index granularity

docs/guides/best-practices/sparse-primary-indexes.md
https://github.com/ClickHouse/clickhouse-docs/issues/3256
These can be smaller.
=> reduce sparse image sizes

docs/cloud/reference/warehouses.md
Introduce the soft limit of 5 services per WH
=> Add number of services per WH soft limit

docs/guides/sizing-and-hardware-recommendations.md
Fix for failing docs check on PR https://github.com/ClickHouse/ClickHouse/pull/78106: https://github.com/ClickHouse/ClickHouse/actions/runs/14010748853/job/39230334946?pr=78106#step:5:950
=> Update sizing-and-hardware-recommendations.md links

plugins/floating-pages-exceptions.txt, sidebars.js
Follow up PR to https://github.com/ClickHouse/ClickHouse/pull/77743?notification_referrer_id=NT_kwDOAoCgIrQxNTM0OTc4MjU4Mjo0MTk4NDAzNA#event-16879601674
=> Add query condition cache to sidebar

docs/cloud/reference/changelog.md
- Adds change log for March 21
=> Cloud change log March 21, 2025

scripts/search/run_indexer.sh
=> Fix run_indexer.sh

package.json, yarn.lock
Reverts ClickHouse/clickhouse-docs#3582
=> Revert "Bump esbuild from 0.25.0 to 0.25.2"

docs/integrations/data-ingestion/clickpipes/postgres/faq.md
=> feat(postgres-cdc): add unexpected datatype faq

docs/cloud/manage/dashboards.md, scripts/settings/autogenerate-settings.sh
=> Append beta, experimental features list to page

docs/cloud/manage/billing/marketplace/overview.md
Updates FAQ on Marketplace Billing page. Closes https://github.com/ClickHouse/clickhouse-docs/issues/3251.
=> Update FAQ on Marketplace Billing

docs/getting-started/example-datasets/amazon-reviews.md, package.json, src/components/CodeViewer/index.tsx, src/css/custom.scss
Example with tweaks to style. Queries aren't as fast as we'd like - we might need the progress bar.
=> make amazon reviews runnable

docs/integrations/data-ingestion/clickpipes/postgres/maintenance.md, sidebars.js
=> feat(clickpipes): add maintenance window for postgres

docs/getting-started/example-datasets/amazon-reviews.md
=> Link to projections

docs/data-modeling/schema-design.md, docs/materialized-view/incremental-materialized-view.md
Addressing a common Kapa question. Docs here aren't great.
=> Joins in materialized views

scripts/settings/autogenerate-settings.sh
Uncomments the fallback install method.
=> Settings generation followup

docs/materialized-view/incremental-materialized-view.md
Best to review the rendered page @tom-clickhouse as the merge is hard to follow - i bumped up `Other Applications`
=> example for mvs and unions

docs/materialized-view/incremental-materialized-view.md, scripts/aspell-ignore/en/aspell-dict.txt
=> mvs and processing order

sidebars.js
=> Remove page which no longer exists

scripts/settings/global-server-settings.sql
This line breaks the indexer 😮‍💨
=> fix search

scripts/settings/mergetree-settings.sql, scripts/settings/session-settings.sql
=> fix setting gen

docs/best-practices/select_data_type.md
minor typo fix: `ContentLicenseLowCardinality(String)` --> `ContentLicense LowCardinality(String)`
=> minor typo fix

docs/integrations/data-ingestion/clickpipes/postgres/faq.md, docs/integrations/data-ingestion/data-formats/json/inference.md, docs/integrations/data-ingestion/data-formats/json/schema.md, scripts/build.sh, scripts/settings/session-settings.sql
Docusaurus build can exit code 1 but the script it's called from is exiting code 0 leading to green CI checks. It's possible to deploy a failing build this way.
Adds error handling to build.sh
=> Fix false positive CI builds

docs/cloud/security/compliance-overview.md
Updating the compliance page to include the new scope for the SOC 2, including privacy, HIPAA and BYOC.
=> 2025 SOC 2 Update

contribute/contrib-writing-guide.md
=> Fixed typo

docs/guides/creating-tables.md, styles/ClickHouse/Headings.yml
=> Language and formatting edits

docs/faq/general/who-is-using-clickhouse.md
=> Fix title casing

docs/cloud/reference/warehouses.md
=> Remove private preview references on warehouses doc

docs/integrations/data-ingestion/clickpipes/postgres/index.md, docs/integrations/data-ingestion/clickpipes/postgres/source/timescale.md, scripts/aspell-ignore/en/aspell-dict.txt
=> [timescale] add link and troubleshooting transparent decompression

knowledgebase/aws-privatelink-setup-for-clickpipes.mdx
=> fix(private-link): indentation for authorized principals

docs/cloud/manage/troubleshooting-billing-issues.md
=> Fix casing of H1

docs/cloud/reference/changelog.md
=> Cloud change log: add update for May 16

docs/integrations/data-ingestion/clickpipes/postgres/faq.md
also moving away from `FOR ALL TABLES` publications
=> [clickpipes] update Postgres FAQ to highlight OpenAPI beta

docs/integrations/language-clients/go/index.md
Fix code style, mistakes and make code listing a bit readable
=> Small changes in code examples

docs/cloud/manage/openapi.md
=> Fix anchor

styles/ClickHouse/Uppercase.yml
=> Add GCS and BYOC to exceptions

docs/cloud/bestpractices/usagelimits.md
=> Formatting: replace list with a table

docs/integrations/data-ingestion/clickpipes/postgres/add_table.md
=> Add H1 to improve searchability

docs/integrations/data-ingestion/clickpipes/kafka.md, docs/integrations/data-ingestion/clickpipes/kinesis.md
Describe new JSON and Variant support for ClickPipes Kafka and Kinesis streams
=> ClickPipes JSON and Variant types

docs/materialized-view/incremental-materialized-view.md
I'm pretty sure the word "not" is missing from this sentence
=> Fixed typo in the UNION example

docs/integrations/language-clients/java/index.md
Updates list of supported data types in Java client. 
Closes: https://github.com/ClickHouse/clickhouse-java/issues/2409
=> updated list of supported data types in Java client

scripts/translate/glossary.csv
=> Add "ClickHouse" to glossary.csv

docs/getting-started/install/install.mdx, src/theme/DocItem/TOC/Desktop/index.js
=> Add a Galaxy event for the closing of the sidebar advert

docs/integrations/language-clients/java/client/_snippets/_v0_8.mdx
- Updates configuration documentation 
- Adds explanation of how to use `setOption` for server settings and custom http headers
Closes https://github.com/ClickHouse/clickhouse-java/issues/2312
Closes https://github.com/ClickHouse/clickhouse-java/issues/2374
=> [JAVA client] Updated configuration documentation

vercel.json
=> Vercel redirects

docs/integrations/data-ingestion/clickpipes/kafka.md
Add Kafka ClickPipe best practices section about compression
Also fixes our private link docs
=> Add Kafka ClickPipe best practices

docs/cloud/manage/backups/export-backups-to-own-cloud-account.md, styles/ClickHouse/Headings.yml
Reverts ClickHouse/clickhouse-docs#3945
=> Revert "Update export-backups-to-own-cloud-account.md"

knowledgebase/vector-search.mdx
Cf. https://github.com/ClickHouse/clickhouse-docs/issues/3910#issuecomment-2985053468
=> KB: Update link to ANN index docs

docs/quick-start.mdx, i18n/jp/docusaurus-plugin-content-docs/current/quick-start.mdx, i18n/ru/docusaurus-plugin-content-docs/current/quick-start.mdx, i18n/zh/docusaurus-plugin-content-docs/current/quick-start.mdx
=> 📃 docs: Modifying MySQL copywriting errors

docs/guides/developer/deduplicating-inserts-on-retries.md
=> add limitations for deduplication

i18n/ru/docusaurus-plugin-content-docs/current/about-us/intro.mdx
=> fix page rendering

docs/integrations/data-ingestion/clickpipes/aws-privatelink.md
Adds a section claryfing supported data source types
=> Supported ClickPipes data source types in RPE doc

docs/guides/developer/merge-table-function.md, scripts/aspell-ignore/en/aspell-dict.txt, sidebars.js
=> merge table engine guide

docs/use-cases/observability/clickstack/config.md, docs/use-cases/observability/clickstack/deployment/_snippets/_json_support.md, docs/use-cases/observability/clickstack/deployment/all-in-one.md, docs/use-cases/observability/clickstack/deployment/docker-compose.md, docs/use-cases/observability/clickstack/deployment/helm.md, docs/use-cases/observability/clickstack/deployment/hyperdx-only.md, docs/use-cases/observability/clickstack/deployment/local-mode-only.md, docs/use-cases/observability/clickstack/example-datasets/remote-demo-data.md, docs/use-cases/observability/clickstack/ingesting-data/collector.md, docs/use-cases/observability/clickstack/ingesting-data/sdks/aws-lambda.md, docs/use-cases/observability/clickstack/ingesting-data/sdks/index.md
Support for JSON in ClickStack
=> Docs for JSON in ClickStack

docs/guides/examples/aggregate_function_combinators/argMaxIf.md
Previously the example data did not give a great example of the argMaxIf functionality. The laptop would have been the returned product irregardless of the sales_count >= 10 condition. I believe my change makes the use of argMaxIf clearer, since the expensive watch is excluded by the condition.
=> Improve argMaxIf.md example numbers

i18n/ru/docusaurus-plugin-content-docs/current/integrations/language-clients/python/index.md
=> Fix .md file

docs/integrations/data-ingestion/clickpipes/mysql/datatypes.md
https://github.com/PeerDB-io/peerdb/pull/3146
=> mysql clickpipes: add note that 00 in day/month is mapped to 01 in clickhouse

README.md
=> chore: add link to website

docs/integrations/data-ingestion/clickpipes/kafka/03_reference.md, docs/integrations/data-ingestion/data-formats/arrow-avro-orc.md, scripts/sed_links.sh
Sed anchors which need to be changed in https://github.com/ClickHouse/ClickHouse/pull/83630
=> Anchor fixes

docs/integrations/index.mdx
Add legal disclaimer to end of integrations page regarding logo usage
=> Add logo disclaimer to integrations page

docs/use-cases/AI_ML/MCP/claude-desktop.md
=> Update claude-desktop.md with video

docs/use-cases/AI_ML/MCP/claude-desktop.md, docs/use-cases/AI_ML/MCP/librechat.md, docs/use-cases/AI_ML/MCP/ollama.md, docs/use-cases/AI_ML/MCP/remote_mcp.md
Everything has ClickHouse MCP in it. Let's simplify.
=> Update sidebar for AI/ML

docs/use-cases/AI_ML/MCP/index.md
Deleting a line that should have been deleted.
=> MCP: remove sentence

.github/workflows/trademark-cla-approval.yml, .github/workflows/trademark-cla-notice.yml
Modifications to trademark addendum workflow to run on pull-request-target
=> Legal: update workflows to run on pull-request-target

.github/workflows/trademark-cla-approval.yml, .github/workflows/trademark-cla-notice.yml
Silent Handling: The workflow now silently ignores any invalid CLA attempts by:
- Logging to console only (for debugging/monitoring)
- Not posting any error comments to users
- Just returning early without any user-visible feedback
Only Acknowledges Valid Signatures: The workflow will only post the confirmation comment and process the approval when:
- The PR author posts the exact required text
- With the correct CLA-SIGNATURE: their_username format
- On a PR that has the cla-required label
=> Legal: more improvements to approval flow

.github/workflows/trademark-cla-approval.yml
According to Claude: " ✅ 412 lines of robust, well-documented workflow code". I'm somewhat sceptical about that...
=> Addendum: further improvements

.github/workflows/trademark-cla-approval.yml
Simplifies the approval workflow to write the signature to file when the `cla-signed` label is added
=> Legal: simplify approval workflow

.github/workflows/trademark-cla-notice.yml
=> Legal: update label naming in trademark-cla-notice

.github/workflows/trademark-cla-approval.yml
Struggling to get the signature commited after the label is added.
Moves everything to one step.
=> Legal: further modifications

.github/workflows/trademark-cla-approval.yml
Fixes: `message: 'Resource not accessible by integration',`
=> Legal: more changes

.github/workflows/trademark-cla-approval.yml
For non-fork PRs:
- Commits signature directly to the PR branch (as before)
For fork PRs:
- Creates a new branch from main with the signature
- Pushes the branch to the main repository
- Automatically creates a PR to merge the signature
- Adds a comment to the original PR linking to the signature PR
=> Legal: update workflow for storing signatures

.github/workflows/trademark-cla-approval.yml
I give up trying to get this workflow to commit the changes to a file. We'll just store them in ClickHouse, as we do for the docs feedback.
=> Legal: store signatures in clickhouse

.github/workflows/trademark-cla-notice.yml
- The workflow currently triggers for PRs without any images added. Making the condition `&&` so that both an image and an integration change are required. Also fixes up a typo.
=> Legal: Update trademark-cla-notice.yml

docs/data-modeling/projections/1_projections.md
Remove semicolon from projection example so you can run it
=> Remove semicolon from projection example

docs/cloud/manage/billing.md
=> fix rendering issue

plugins/floating-pages-exceptions.txt, sidebars.js
Removes the new page from the exceptions list and adds it to sidebars.js. Also updated the internal wiki in notion with the process.
=> add new page to sidebars.js

docs/cloud/manage/replica-aware-routing.md
Fixes a link to the wrong place
=> correct link replica-aware-routing.md

src/components/Navigation/styles.scss
=> Remove animations

docusaurus.config.en.js, scripts/search/settings.json, src/theme/SearchBar/index.js
I adjusted the Algolia Indexing rules (for the dev env) and added an ask AI button that links to our Kapa chat bot widget.
=> 4187 improve algolia search infra

docs/integrations/data-ingestion/kafka/confluent/confluent-cloud.md
The correct instructions are below https://github.com/ClickHouse/clickhouse-docs/compare/confluent-cloud?expand=1#diff-e6ce65cbfbbe441fc30cf64ab1c1d1dbe1699d91ca18dfbe615e4a83da7007bbR45-R46
=> remove duplicate entry for Confluent connector

docs/use-cases/AI_ML/ai-powered-sql-generation.md
=> AI powered SQL generation

i18n/ru/docusaurus-plugin-content-docs/current/interfaces/grpc.md
=> Fix translation bug

docs/integrations/language-clients/python/index.md
Fixes a small formatting issue
=> Fix headers

docs/cloud/manage/api/api-overview.md
Updated api overview doc with new pricing migration information for TF and OpenAPI
=> Updated api overview doc with new pricing migration information

docs/cloud/reference/changelog.md
=> Cloud change log August 8

docs/cloud/reference/changelog.md
=> Cloud: add change log 13 August

scripts/translate/glossary.csv
Updates the glossary with Spanish translations from an LLM
=> Update glossary.csv with Spanish

docs/getting-started/example-datasets/laion.md
- Remove outdated `Annoy` references
- Explain new syntax for creating vector similarity index
- Corrections to Python code after testing
- More example datasets for vector search on the way
=> Remove references to annoy, update new info in laion.md

docs/cloud/reference/changelog.md
=> Docs: change log for 22 Aug

sidebars.js
Purely cosmetic change to reduce confusion
=> MySQL sidebar: fix bad merge

docs/guides/examples/aggregate_function_combinators/sumForEach.md
=> Rename header from 'sumArray' to 'sumForEach'

docs/use-cases/observability/clickstack/example-datasets/kubernetes.md
=> Adding video

plugins/floating-pages-exceptions.txt
Need it for this PR https://github.com/ClickHouse/ClickHouse/pull/86662
=> Add allocation-profiling-old.md to exceptions

docs/cloud/onboard/index.md
Add a link the Cloud getting started section to the troubleshooting guide.
=> Cross linking: link troubleshooting guide

docs/cloud/features/05_admin_features/upgrades.md, scripts/aspell-ignore/en/aspell-dict.txt
Adding clarification for compatibility settings docs
=> Clarifying compatibility settings docs

docs/cloud/reference/03_billing/01_billing_overview.md
=> adding closing tag to note

docs/cloud/reference/03_billing/01_billing_overview.md
Unescaped Dollar Sings Broke Formatting.
=> escaping $ signs

scripts/search/index_pages.py, scripts/search/settings.json, src/theme/SearchBar/utils/searchConfig.js
Reverts ClickHouse/clickhouse-docs#4519
=> Revert "adding doc_type ranking so references and guides appear first"

scripts/search/index_pages.py, scripts/search/settings.json, src/theme/SearchBar/utils/searchConfig.js
Reverts ClickHouse/clickhouse-docs#4538
=> Revert "adding doc_type ranking so references and guides appear first"""
