ClickHouse/clickhouse-docs

docs/en/guides/sre/configuring-ssl.md
Found Raft ports can also be set to secure, added option.
from this changelog:
https://clickhouse.com/docs/en/whats-new/changelog/2021/#:~:text=keeper_server.raft_configuration.secure
=> add secure flag to enable SSL on Raft ports

docs/en/integrations/mysql/mysql-with-clickhouse-database-engine.md
- As title, fixing the MaterializedMySQL link.
=> Fix MaterializedMySQL link

docs/en/integrations/kafka/kafka-connect-http.md, docs/en/integrations/kafka/kafka-connect-jdbc.md
Links got broken in docs move to `en`.
=> Fix references to kafka code

docs/en/whats-new/changelog/2017.md, docs/en/whats-new/changelog/2018.md, docs/en/whats-new/changelog/2019.md, docs/en/whats-new/changelog/2020.md, docs/en/whats-new/changelog/2021.md, docs/en/whats-new/changelog/2022.md, docs/en/whats-new/changelog/_category_.yml
Changelogs were all grouped under 2022, moves like so:
=> move changelogs by year

docs/en/integrations/dbt/dbt-view-model.md
Error:
```
$ dbt run            
12:21:48  Running with dbt=1.1.1
12:21:48  Partial parse save file not found. Starting full parse.
12:21:50  Encountered an error:
Compilation Error in model actor_summary (models/actors/actor_summary.sql)
Model 'model.imdb.actor_summary' (models/actors/actor_summary.sql) depends on a source named 'imdb.genres' which was not found
```
Example of `schema.yml` from DBT's docs:
https://docs.getdbt.com/reference/configs-and-properties#example
=> Fix yaml indentation on DBT guide

package.json, yarn.lock
In order to load code blocks from source code files (rather than embed the code in Markdown files) we need `raw-loader` and `webpack`.  These are added in this PR.  This will allow files (for example, the file `connect_test.go`) with this markdown:
```
---
sidebar_label: GO
---
import CodeBlock from '@theme/CodeBlock';
import conn_test from '!!raw-loader!../../../_clients/go/tests/conn_test.go'    
<CodeBlock language="go">{conn_test}</CodeBlock>   
```
`go/examples` and `go/tests` will get copied to `clickhouse-docs/docs/_clients/go/`, 
This is an interim step while I work on importing sections of a source file marked with "start" and "end" comments.
cc: @gingerwizard
=> add raw-loader for source files

docusaurus.config.js, src/css/custom.css
Here is what it will look like:
=> Make docs nav look like clickhouse.com nav

src/css/custom.css
Some of the detail of transparent images were being lost in light mode with a white background.  This change uses a transparent (none) bg in light mode and a white bg in dark mode.
=> use none for bg color in light

docs/en/guides/developer/transactional.md
I made very few changes, the two that I recall are changing `max_insert_size` to `max_insert_block_size`, and changing the default from 1,000,000 rows to 1,048,576 rows.
=> add notes about ACID transactions

docs/en/quick-start.mdx
I used a headless Ubuntu to run this tutorial, only to find that this tutorial relies on a web UI. The CLI client comes much later in the tutorial, and I have to turn to the web UI to create the database first. So it might be a good idea to introduce the clients earlier and guide developers to run the SQL all the way down?
=> Introduce the clients earlier for the quickstart guide

src/css/custom.css
The deepnote button was huge suddenly, not sure how.  This fixes it.
=> set image width to fit the image

src/css/custom.css, static/img/logo_without_text.svg
The ClickHouse logo was not displaying in FireFox. Additionally the width of the header was not reaching the full width of the page. This PR fixes both of these issues. 
Sidenote: We were using `-webkit-fill-available` which isn't supported by firefox browsers, I've been investigating why we were using it but could not find a good reason. I've replaced it with `width:100%` and have tested across browsers and device sizes and don't see any visual degradation.
=> Fixing missing logo in firefox.

src/css/custom.css
Related to: https://github.com/ClickHouse/clickhouse-docs/pull/299 which didn't produce the desired result. 
After a little more research I noticed that Firefox needs the height and width to be a little more verbose than other browsers. While the sizing and viewBox provided in the logo SVG itself worked locally, something in the build process meant that in production. the sizes weren't being recognised. This is fixed by verbosely adding desired height and width via css.
=> Adding exact height, width to logo SVG

docs/en/integrations/sql-clients/clickhouse-client-local.md
Install instructions for `clickhouse client` and `clickhouse local` on Linux, macOS, Windows with WSL 2.
These are just install instructions, in the Next Steps there are links to the details about the two commands and a dataset that makes quite a bit of use of local and client.
@Ryado I think local deserves a spot in the integrations table, and maybe the table entries for client and local should point to this page.
cc: @gjones @guykoh @alexey-milovidov  @Ryado
=> add install instructions for client and local for windows, mac, linux

docs/en/guides/sre/s3-multi-region.md
We have only one shard for the cluster described at [Replicating a single shard across two AWS regions using S3 Object Storage](https://clickhouse.com/docs/en/guides/sre/s3-multi-region) -> The value of `clickhouse.macros.shard` must be the same for all nodes.
=> Fix `macros` note for S3 multi region doc.

docs/en/guides/developer/mutations.md
ClickHouse 22.8 supports `DELETE FROM`, which should be noted for users.
=> Add note about delete from

docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-design.md
Fixed typo at section WHY MARK FILES.
=> Fixed typo: URL.bin instead of URL.data

docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-cardinality.md, docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-design.md, docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-intro.md, docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-multiple.md, docs/en/guides/improving-query-performance/sparse-primary-indexes/sparse-primary-indexes-uuids.md
links should include the `.md`
@tom-clickhouse we are seeing reports of 404's on these pages.  This is probably caused by not having the `.md` in the links.  I know you are working on these docs this week, so please pull your working copy after I fix these.
=> update links to fix 404s

docs/en/integrations/language-clients/nodejs.md
* Updated API
* Added a bit more examples and know-how
* Reformat the document
* Fix code snippets so those are valid TypeScript and more copy-paste friendly
* Spelling and wording fixes
=> Update Node.js docs for 0.0.5 release

docs/en/_snippets/_add_superset_detail.md
In some of the tutorials I expect we will build visualizations in Grafana, Superset, Metabase, etc. Rather than send people to a new page to install the visualization software we can use an expandable detail section in the current doc and include the instructions there.  This PR adds a detail section for Apache Superset.  When included in a tutorial, for example the cell tower dataset, this is what it looks like when expanded:
and when closed (the default):
=> adds reusable snippet for Superset

docs/en/manage/backups.mdx, docusaurus.config.js
This must be merged with https://github.com/ClickHouse/ClickHouse/pull/42666
Because we include the self managed and cloud backup instructions into a single file with tabs the self managed file is renamed from backup.md to _backup.md to remove it from the side nav.
This PR does:
- add redir
- change import filename to_backup.md
=> move operations/backup to an include file

docs/en/whats-new/security-changelog.md
Previously there were 2 heap buffer overflow vulnerabilities that was reported to us through our Bugbounty program. 
Core team immediately jumped on it within 2 days and addressed the issue. 
It took a while to get the CVE submission through but we have them now for tracking and to credit the original researcher.
=> Adding details for CVE-2022-44011 and CVE-2022-44010

docs/en/guides/sre/user-management/users-and-roles.md
Instructions for creating an admin user.  The workflow might be something like this:
- Create a ClickHouse Cloud service
- Create a non-default admin role
- Create a database for a project
- Create a user for a project, and assign the admin role for the project DB to the project user
- Invite a Developer user to the org
=> add cloud specifics for admin role / user

yarn.lock
Fixes this in the build output:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
=> update browser list

docs/en/integrations/data-ingestion/s3/configuring-s3-for-clickhouse-use.md
The configuring s3 for clickhouse doc seems to have two separate create statements. Looks to be a duplicate. Removed the extra create statement.
=> Remove duplicate create statement in configuring-s3-for-clickhouse-use.md

docs/en/integrations/data-ingestion/etl-tools/redshift/redshift-pivot-to-clickhouse.md
Adds an intermediary step to https://clickhouse.com/docs/en/integrations/redshift/redshift-pivot-to-clickhouse/, creating the correct table structure before inserting data.
=> Add create table instructions to Redshift to ClickHouse migration

docs/en/quick-start.mdx
I think for people who landed to documentation from Google it is more valuable to explain what ClickHouse Cloud is first, instead of bringing them straight to sign-up (which is still linked below in the instruction + main CTA on that /cloud).
=> Tune cloud links in Quick Start

docs/en/integrations/language-clients/nodejs.md
The parameter `user` should be `username` per instructions further up and real implementation.
=> Fix createClient example

docs/en/tutorial.md
Current query seems to be grouping by hour, not by minute. 
Indeed, out of 2 million rows in the table, only ~14K have this value above 0. 
```
SELECT count()
FROM trips
WHERE truncate(dateDiff('second', pickup_datetime, dropoff_datetime) / 3600) > 0
Query id: e1c973b4-cda6-4917-86f3-45501a1b4049
┌─count()─┐
│   13932 │
└─────────┘
1 row in set. Elapsed: 0.023 sec. Processed 2.00 million rows, 16.00 MB (88.67 million rows/s., 709.36 MB/s.)
```
=> Fix trip duration query in the first Clickhouse tutorial

docs/en/cloud/bestpractices/bulkinserts.md
The buffer table engine is a great option when you are sending a large number of insert request with a low number of rows on each.
=> Replace external kafka option by Buffer table engine

docs/en/integrations/data-ingestion/kafka/kafka-clickhouse-connect-sink.md, docs/en/integrations/data-ingestion/kafka/kafka-connect-http.md, docs/en/integrations/data-ingestion/kafka/kafka-connect-jdbc.md, docs/en/integrations/data-ingestion/kafka/kafka-connect-options.md, docs/en/integrations/data-ingestion/kafka/kafka-vector.md
Move docs from [README](https://github.com/ClickHouse/clickhouse-kafka-connect#readme) to the website
=> add docs for ClickHouse Kafka Connect Sink

contrib-writing-guide.md
(1) is an older and seemingly unmaintained version of (2). Let's not maintain two documents with the same content.
Some information existed in (1) but not in (2). This commit integrates it into (2). A separate PR will replace (1) by a (textual) pointer to (2).
EDIT: That separate PR is https://github.com/ClickHouse/ClickHouse/pull/45472
(1) https://github.com/ClickHouse/ClickHouse/blob/master/docs/tools/README.md
(2) https://github.com/ClickHouse/clickhouse-docs/blob/main/contrib-writing-guide.md
=> Integrate some tidbits from duplicate doc writing guide into this guide

docs/en/integrations/data-ingestion/data-formats/binary.md, docs/en/integrations/data-ingestion/data-formats/csv-tsv.md, docs/en/integrations/data-ingestion/data-formats/json.md, docs/en/integrations/data-ingestion/data-formats/parquet-arrow-avro-orc.md, docs/en/integrations/data-ingestion/data-formats/sql.md
Added tips on `file()` usage as Dale suggested. Also fixed a link to JSON article in the tip box.
=> Tips on file() & fixed JSON link

docs/en/cloud/reference/changelog.md
had a link using `https://click...` and we need to use `/docs/en/...` to link to markdown files so that URLs are checked.
=> link to markdown file

docs/en/integrations/data-ingestion/kafka/cloud/confluent/index.md, docs/en/integrations/data-ingestion/s3/s3-table-engine.md
report
```
htmltest started at 07:44:55 on build/build/docs/en/integrations
========================================================================
Cannot access 'build/build/docs/en/integrations', no such directory.
❯ vi .htmltest.yml
❯ htmltest
htmltest started at 07:45:12 on build/docs/en/integrations
========================================================================
airbyte-and-clickhouse/index.html
Get "http://localhost:8000/": dial tcp [::1]:8000: connect: connection refused --- airbyte-and-clickhouse/index.html --> http://localhost:8000/
kafka/cloud/confluent/index.html
Non-OK status: 404 --- kafka/cloud/confluent/index.html --> https://github.com/ClickHouse/clickhouse-docs/tree/main/docs/en/integrations/kafka/code/connectors/http_sink
s3/s3-table-engine/index.html
Non-OK …
```
=> fix broken links in integrations docs

docs/en/integrations/language-clients/java/r2dbc.md
Page https://clickhouse.com/docs/en/integrations/language-clients/java/r2dbc has the incorrect title: the article about R2DBC driver should has the title 'R2DBC' instead of 'JDBC'.
=> Fixes title in R2DBC driver page

docs/en/integrations/index.mdx, docs/en/quick-start.mdx, docs/en/tutorial.md, docusaurus.config.js
Having the parent of the integrations page as "integrations" boosts the page ranking.
So, while https://clickhouse.com/docs/en/integrations/ ranks low, https://clickhouse.com/docs/en/integrations/intro should rank higher
=> modify path to integrations index

docs/en/cloud/bestpractices/asyncinserts.md
docs repo side PR (1/2) related that adds async_insert_max_query_number to the async insert guide
this PR is completed by PR in Clikchouse repo (will post shortly once I'll have the link :sweat_smile:)
related Issue :https://github.com/ClickHouse/docs-private/issues/23
goes in pair with: https://github.com/ClickHouse/ClickHouse/pull/47431 
closes: https://github.com/ClickHouse/docs-private/issues/23
=> Document use of add async_insert_max_query_number

knowledgebase/recreate_table_across_terminals.md
This is NOT a recommended practice to migrate data from one database to another and it should NOT be used for production data migration.
This is simply intended as a quick and dirty way to recreate small amount of data when developing across multiple environments.
=> [KB] How to quickly recreate a small table across different terminals

docs/en/quick-start.mdx
- Fixes the link to `Kafka` table engine (`/docs/en/engines/table-engines/integrations/kafka`)
=> Fix kafka table engine link in `docs/en/quick-start.mdx`

src/css/colors.scss, src/css/custom.scss, src/css/default.scss
Closes: https://github.com/ClickHouse/design/issues/56. Details areas have dark background in light mode, so the default text colour for light mode was not showing up correctly. This PR checks to see if a h1-h3 header is in a details area, and if so, makes it light in colour. If it, the header remains dark.
=> Fixing colour issues on anchors in details

docs/en/integrations/language-clients/python/index.md
See the discussion in https://github.com/ClickHouse/clickhouse-connect/issues/91
Today I tried to find the community driver in our documentation and failed to find anything but https://clickhouse.com/docs/en/integrations/python and related pages. So let's mention it on that page.
=> Add a note about python drivers

docs/en/guides/best-practices/skipping-indexes.md
spelling of this setting in documentation did not match reality. it's actually 'force_data_skipping_indices' - e.g.:
select * from e4 where has(val,7) settings force_data_skipping_indices='idx_val';
=> force_data_skipping_indexes -> force_data_skipping_indices

docs/en/cloud/manage/openapi.md, docs/en/cloud/manage/postman.md, sidebars.js
- puts API content together:
- ClickHouse Cloud API
- Endpoints API      <------------------------ @GMartinez-Sisti this is your doc; please sync with @krithika-ch 
- Postman use w/ ClickHouse Cloud
- Renames OpenAPI for ClickHouse to ClickHouse Cloud API
Note: If you want a change to the title of the swagger docs, that is done by editing the `title` in control plane repo `{ "openapi": "3.0.1", "info": { "title": "OpenAPI spec for ClickHouse Cloud", "version": "1.0" }, `
New nav:
=> rename and move APIs

docs/en/guides/developer/cascading-materialized-views.md
The current formatting of the list does not result in one item per line, but rather all the lines being concatenated after one another:
```
You could choose one of these options: write queries that will read and aggregate the data during the SELECT request prepare the data at the ingest time to a new format Prepare the data at the time of ingest to a specific aggregation.
```
The desired outcome was likely
```
You could choose one of these options:
write queries that will read and aggregate the data during the SELECT request 
prepare the data at the ingest time to a new format 
Prepare the data at the time of ingest to a specific aggregation.
```
The minor difference in this PR is that the list will be formatted.
```
You could choose one of these options:
- Write queries that will read …
```
=> Improve cascading materialized views formatting

docusaurus.config.js
This page (https://clickhouse.com/docs/category/cloud-reference) must have existed at some point because it shows up in Google searches, but it no longer exists, so redirecting.
=> Fix broken Cloud link

docs/en/deployment-guides/horizontal-scaling.md, docs/en/deployment-guides/replicated.md
This PR rewords our statement for running keeper nodes in production to strongly recommended on dedicated hosts
depends on https://github.com/ClickHouse/ClickHouse/pull/49841
=> Strongly recommend dedicated keepers in production

docs/en/cloud/security/aws-privatelink.md
The terraform code has the wrong type of quotes in the line starting with service_name which make the entire code invalid
=> Fixed wrong type of quotes of the terraform code example

docs/en/integrations/language-clients/nodejs.md
As a follow-up from [#157](https://github.com/ClickHouse/clickhouse-js/issues/157), a found issue should be noted in the docs.
=> Disable compression to query Live Views using `clickhouse-js` adapter

contrib-writing-guide.md
This commit updates `contrib-writing-guide.md` to have developers make sure that they install yarn v1. This information is helpful because the latest version of yarn doesn't work well.
=> Update contrib-writing-guide.md to encourage to use yarn v1

docs/en/integrations/language-clients/python/index.md
There is no query_column_rows_stream method in the source code, but the query_row_block_stream method, which is in the source code, fits the description.
=> Method name fix in python documentation

src/css/custom.scss
Let's see if it works...this should keep the left-hand nav in place as a user scrolls down a long docs page
=> Add scrollbar to left-hand nav

docs/en/guides/sre/configuring-ssl.md
closes https://github.com/ClickHouse/ClickHouse/issues/51028
See above issue for details, the cert was not being used for raft communication until the `<secure>1</secure>` was moved up a level.  Thanks to @AlmostIvanSidorov for debugging this.
=> fix raft config

docs/en/about-us/adopters.md
Replaced link to Youtube presentation (which is kind of long, and Clickhouse reference is buried in the middle) to VLDB'22 paper and slides, where Clickhouse reference is prominent
=> Update links for Firebolt

src/css/custom.scss
It was leaving odd blank space at the bottom. Let's try 100% and see how it works
=> Fix scroll bar height

copyClickhouseRepoDocs.sh
Hi Vineeth, I think that you wrote the script to support Vercel build.  We only need the master branch of ClickHouse/ClickHouse.  This saves 88% of the clone.
=> only grab master, 1/12th of the size

docusaurus.config.js
It appears that some of the redirects may be adding extra slashes to URLs, and when these get indexed into Algolia the returned search results are:
- duplicates 
- causing 404's
This PR removes trailing slashes on redirects for dir names
cc: @Felixoid
=> some redirects add extra slashes

knowledgebase/Insert_select_settings_tuning.md
This expert level KB, credit of @DerekChia enumerates settings that might help avoiding the TOO_MANY_PARTS error when doing
```SQL
INSERT INTO...SELECT FROM...
```
=> [kb] insert select settings to avoid TOO_MANY_PARTS

docs/en/cloud/security/gcp-private-service-connect.md
this PR adds the important disclaimer, that enabling PSC in GCP service is reserved only for Production tiers.
=> [Cloud][PSC] Add disclaimer PSC only on Prod

knowledgebase/check-query-cache-in-use.md
This PR updates the `How can I check that query cache is being used in my query?` removing the notion of experimental feature and providing more means to verify whether cache is in use for queries.
=> [kb] Updates to query cache KB

docs/en/quick-start.mdx
Judging from the rest of the tutorial, SQL commands should be contained within ` codeblocks. In [step 6](https://clickhouse.com/docs/en/getting-started/quick-start#6-query-your-new-table) the SELECT command is used but isn't in a codeblock. This PR fixes that.
=> Put SELECT command into codeblock.

docs/en/integrations/language-clients/go/index.md
In Go client docs Parameter Binding section is included in sidebar for `database/sql` api, but not for client-specific.
=> make Parameter Binding appear on sidebar

docs/en/guides/sre/keeper/index.md
Add a note that `/keeper/config` is a virtual node, fix typos
=> Enhance changes to `reconfig` docs

docs/en/guides/developer/deduplication.md
Suggest using `insert_deduplication_token` in Deduplication Strategies guide if deduplication fails
Context: https://clickhouse-inc.slack.com/archives/C02F2LML5UG/p1689611489370029
=> More details on insert_deduplication_token

docs/en/integrations/language-clients/python/index.md
The function name is `create_insert_context`, not `get_insert_context`. Fixes the typo to clarify.
Source code: https://github.com/ClickHouse/clickhouse-connect/blob/cfed21396dfe5efc9ae52ffcb48dfdfbcd99ff61/clickhouse_connect/driver/client.py#L608
=> Fix a python typo regarding InsertContext usage

docs/en/cloud/manage/scaling.md
=> Updated scaling.md for revised scaling docs

docs/en/_snippets/_aws_regions.md, docs/en/cloud/security/aws-privatelink.md
Privatelink doc updates for new cell in us-east-1
Corresponding support knowledge base updated here: https://github.com/ClickHouse/internal-knowledge-base/issues/24
Description: we are introducing a new cell in us-east-1 production in aws. Customer before creating a private link VPC endpoint needs to know which cell their instance is in, so that they know which VPC endpoint service their privatelink needs to connect against.
As a result, we provide c0 and c1 two service DNS endpoints for customer, and ask customer to create support case to ask about cell before set up private link endpoint on their end.
This is just a temporary measure for a few weeks, before we have automated privatelink set up for customers.
=> Privatelink doc updates for cells

docs/en/guides/best-practices/sparse-primary-indexes.md
Sometimes "it's" is correct english. To check a specific instance, replace "it's" with "it is". If the sentence still makes sense, "it's" is totally fine! If it doesn't, "it's" is incorrect and "its" is correct.
This PR replaces some incorrect "it's" with "its".
I noticed this while reading this specific docs page. I scanned the repo for all uses of "it's" expecting to find more errors, but these were the only ones I found!
=> fix: Replace some it's with its

docs/en/guides/best-practices/skipping-indexes.md
On https://clickhouse.com/docs/en/optimize/skipping-indexes there's a section where the double underscores cause Markdown to incorrectly render italics.
Wrapping these texts in `code blocks` will resolve the issue.
=> fix: Resolve underscores causing italics

docs/en/migrations/bigquery.md, sidebars.js
This is a simplified doc of the migration section from this blog post:
https://clickhouse.com/blog/clickhouse-bigquery-migrating-data-for-realtime-queries#exporting-data-to-gcs
=> Initial BigQuery migration guide

package.json
This PR fixes error when executing 
`yarn prep-from-master`
on linux
tested on linux mint/ubuntu
```
user@zeus:/opt/clickhouse-docs$ uname -a
Linux zeus 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
nellicus@zeus:/opt$ git clone https://github.com/ClickHouse/clickhouse-docs
Cloning into 'clickhouse-docs'...
remote: Enumerating objects: 27725, done.
remote: Counting objects: 100% (2922/2922), done.
remote: Compressing objects: 100% (1832/1832), done.
remote: Total 27725 (delta 1145), reused 2773 (delta 1061), pack-reused 24803
Receiving objects: 100% (27725/27725), 262.58 MiB | 16.49 MiB/s, done.
Resolving deltas: 100% (15576/15576), done.
nellicus@zeus:/opt$ cd clickhouse-docs/
nellicus@zeus:/opt/clickhouse-docs$ git branch
* main …
```
=> Fix prep-from-master on linux

contrib-writing-guide.md
add OS specifc instructions on how to install npm/yarn to build the docs on OSx/Linux
=> [building-docs] os specific npm/yarn instructions

docs/en/integrations/language-clients/js.md
* Updated client <-> ClickHouse versions
* Rearranged "web limitations"
* Add file streaming examples links
* Add Parquet to the support formats table
NB: I think that table is currently missing the "Output (Stream)" column, which will be added as a follow-up, as Parquet as text probably does not make much sense.
See also: https://github.com/ClickHouse/clickhouse-js/pull/208
=> Add Parquet and file streaming docs for CHJS

docs/en/guides/sre/user-management/ssl-user-auth.md
The given example does not work for me. There needs to be a `<client>` level in the middle between `<openSSL>` and cert files.
=> Fix client ssl cert auth example config.

docs/en/cloud/security/security-companion-guide.md
Updating password settings to match changes from Auth0 and remove the notice about Google Password Manager since this is no longer an issue.
=> Auth0 - Updating Password Settings

docs/en/integrations/data-ingestion/kafka/confluent/custom-connector.md, docs/en/integrations/data-ingestion/kafka/index.md, docs/en/integrations/data-ingestion/kafka/msk/index.md, sidebars.js
The current sidebar creates the impression there is only 1 way to use Kafka with ClickHouse. I extended sidebar with a link to a cover page and a few recommended options:
- Clickpipes
- Kafka Connector Sink
- Kafka Connector Sink on Confluent
- Kafka Connector Sink on MSK
- Vector
=> add more Kafka options to the sidebar

docusaurus.config.js
=> Removes lingering reference to analytics.js.

docs/en/guides/sre/keeper/index.md
I struggled with this a bit when starting ClickHouse as the documentation didn't specify where to add `<keeper_server>`. I added an explicit mention of the `clickhouse-server/config.xml` to help avoid people mistaking the `clickhouse-keeper/keeper_config.xml` (which also contains `<keeper_server>` definitions). 
I think this is a small change that will help newer users who may be unaware of the `clickhouse-server/config.xml` file.
=> Clickhouse keeper: Add name of clickhouse-server/config.xml

docs/en/cloud/security/gcp-private-service-connect.md
due to bug in API customers cannot use self-service approach for GCP. reverting PSC doc to previous version
=> revert PSC docs

docs/en/guides/developer/cascading-materialized-views.md
This documentation addition came from wanting to use Materialized Views to recreate logic similar to `UNION ALL` and `GROUP BY`. There are a couple discussions of this in [discussions](https://github.com/ClickHouse/ClickHouse/issues/17058) and on Slack, but no examples of combining multiple source tables into the same `target` table were on the official documentation. 
I was really excited to learn this feature exists, so thought it would be appropriate to include an example in the Materialized View documentation for ClickHouse.
=> Example of combining multiple source tables to target table

docs/en/integrations/language-clients/java/index.md
In reference to ClickHouse/clickhouse-java#1465, we improved and sharpened our documentation regarding named parameters in our native Java client.
=> Document Named Parameters in java native client

docs/en/integrations/language-clients/java/index.md
The build process ran into some issues causing Vercel to not serve new versions of the docs. This PR aims to fix these issues so that the docs site serves the correct content.
=> Fixes link in Java Integration page.

docs/en/integrations/language-clients/go/index.md
Now it looks \`connect(), instead of `connect()`
=> Fix inline code typo

docs/en/guides/sre/network-ports.md
Fix spelling mistakes and remove mention of the insecure port 8123 for JDBC/ODBC.
=> Update network-ports.md: Fix spelling and remove confusion

src/css/custom.scss, src/theme/DocItem/TOC/Desktop/styles.module.css
Fixes : https://github.com/ClickHouse/clickhouse-docs/issues/1762
Now TOC section will be fixed at the top
and increased the font size for a better view
=> Fix TOC scroll and increase highlight

docs/en/whats-new/roadmap.md
Closes https://github.com/ClickHouse/clickhouse-docs/issues/1818.
=> Adds 2024 roadmap.

docusaurus.config.js
Control Plane devs found an old link in their UI. Users who go to `/en/home` are now directed to `/docs`.
=> Adds redirect from `home` to `docs`.

README.md
Adds steps into `readme.md` to build the site using a local version of [the `clickhouse/clickhouse` repo](https://github.com/clickhouse/clickhouse) using `prep-from-local`.
=> Adds steps to prep-from-local.

docs/en/integrations/language-clients/js.md
- Added an example of how to insert data to a database different from the one provided to the client instance
- Added an example for including/excluding columns for inserts
- Updated `InsertParams` interface overview
- Added a note about read-only users
- Removed web client Keep-Alive limitation as it is now configurable
- Updated Keep-Alive entry
- Bumped versions
- Fixed a dead link
=> Update clickhouse-js docs as of 0.2.8

docs/index.md
Changes a link on the homepage to go somewhere useful instead of a lovely 404 page.
=> Updates single-node-deployment option on homepage.

knowledgebase/schema_migration_tools.md
There are a number of PRs open to add support to ClickHouse, but as the time of this writing (Jan, 17th 2024) Flyway doesn't support ClickHouse yet, and trying to use it results in the error
```
Unsupported Database: ClickHouse 23.8
```
It is therefore misleading to have the link in the docs, as one might trust this information during an evaluation phase and get caught by surprise later on.
=> Remove Flyway from list of migration tools supporting ClickHouse

knowledgebase/schema_migration_tools.md
Reverts ClickHouse/clickhouse-docs#1857
As of version 10.7.0 Flyway [officially supports ClickHouse](https://documentation.red-gate.com/flyway/flyway-cli-and-api/supported-databases/clickhouse-database) 🎉
=> Add Flyway to list of migration tools supporting ClickHouse

docusaurus.config.js
broken by https://github.com/ClickHouse/clickhouse-docs/pull/1864
needs to be tested.
I have a few questions:
- does redirect plugin work locally? it doesn't seem to work for me
- don't we have automation to detect broken links?
=> fix broken link

docs/en/integrations/data-ingestion/clickpipes/index.md
We're soon going to move beyond Kafka and Managed Kafka Providers. 
This is the first step to deemphasise Kafka as the only source and just make instructions more generic.
=> [ClickPipes] De-emphasise Kafka in docs

docs/en/_snippets/_clickhouse_mysql_cloud_setup.mdx, docs/en/integrations/data-visualization/looker-studio-and-clickhouse.md
* Provide more hints and explanations, better examples with custom profiles
* Move it from Looker Studio to `_clickhouse_mysql_cloud_setup.mdx` cause it's useful for every tool and it should be in every doc entry where this snippet is included.
=> Clarify multiple MySQL users in the Cloud doc

docs/en/integrations/data-ingestion/kafka/kafka-clickhouse-connect-sink.md
This PR depends on https://github.com/ClickHouse/clickhouse-kafka-connect/pull/323
Documentation must be updated as soon as mentioned PR is merged.
=> docs: update supported types by `clickhouse-kafka-connect-sink`

docs/en/integrations/data-ingestion/clickpipes/index.md
Adds a note on no custom CA certificates to the ClickPipe docs.
=> Adds note on no custom CA certificates.

docs/en/guides/troubleshooting.md
- Since the `apt-key` is deprecated in the latest Debian-based distributions, it will occur the GPG importing keys issue.
- It's related to the https://github.com/ClickHouse/ClickHouse/pull/60401.
- According to the above PR, creating the temporary GPG directory issue is related to the gpg version.
=> Add troubleshooting for apt-key and gpg

docs/en/integrations/language-clients/java/index.md
Adds instructions and an example for setting the socket timeout and connection timeout options with `ClickHouseClient` and `ClickHouseClientOption`. This is necessary to support long-running data insert operations.
=> docs: add socket and connection timeout options to JDBC large insert

docs/en/integrations/language-clients/python/index.md
- As title, fixing the Python code snippets for declaring the `tuple` type.
=> Fix Python code syntax for the tuple type

docs/en/integrations/data-ingestion/kafka/index.md
Added Redpanda Cloud, a 3rd party Kafka API-compatible cloud platform, as a potential upstream for ClickHouse.
=> Adding Redpanda Cloud as a 3rd party cloud based Kafka connection

docs/en/integrations/language-clients/js.md
* Update the docs according to the [upcoming 0.3.0 release](https://github.com/ClickHouse/clickhouse-js/blob/main/CHANGELOG.md#030-nodejs-only).
* Fixed dead links
* Rewritten outdated sections
* Rewritten certain sections for clarity
* Added more information about the ResultSet
* Added the [examples overview](https://github.com/ClickHouse/clickhouse-js/blob/main/examples/README.md#overview) link
* Added the "Contact Us" section
* Removed "Endless streams" examples, as using async inserts will be a much safer option for the same use cases
* Highlighted and clarified certain features (for example, JSON _ClickHouse format_ cannot be streamed, but JSONEachRow can be; it can lead to confusion if one is unfamiliar with CH formats and could conclude that the client does not support streaming …
=> Update the JS client docs - 0.3.0

docs/en/guides/troubleshooting.md
- Sine this https://github.com/ClickHouse/ClickHouse/pull/61252 is merged and find proper and simplified solution, it should remove these troubleshooting steps because they're not necessary.
=> Remove unnecessary steps about troubleshooting GPG

docs/en/integrations/data-visualization/grafana/config.md, docs/en/integrations/data-visualization/grafana/index.md, docs/en/integrations/data-visualization/grafana/query-builder.md
Added some changes for v4.0.3 as well as some cleanup from the previous PR review:
- Added new section for Macro functions
- Fixed numbering of steps on quick start guide
- Changed phrasing config options so people don't mistake it as a copy/paste usable example
- Added links to referenced ClickHouse SQL statements
- Added link to our OpenTelemetry exporter in the OTel config section
- Misc. code review notes + changes
=> Update Grafana docs for v4.0.3

docs/en/integrations/language-clients/js.md
JSONStrings is marked as [acceptable input here](https://clickhouse.com/docs/en/interfaces/formats), but at least with CHJS, it is not accepted as input for insert operations.
```
ClickHouseError: Format JSONStrings is not suitable for input. 
code: '85',
type: 'FORMAT_IS_NOT_SUITABLE_FOR_INPUT'
```
=> CHJS: Fix data formats table

docs/en/whats-new/security-changelog.md
Our LTS versions will be updated in the next release but unfortunately the latest update (14th March) missed this fix by 1 day (Backported on 15th March) but the team is working on cutting another release soon.
=> Adding CVE-2024-22412

docs/en/integrations/data-ingestion/clickpipes/index.md
Reference table for ClickPipes virtual columns available in Kafka-like datasources
=> Add reference for available Kafka virtual columns

docs/en/integrations/data-ingestion/clickpipes/index.md
- Adds overview of path-finding syntax
- Adds a note on the 1GB limitation
=> [ClickPipes] Document S3/GCS Pipe limitations

docusaurus.config.js, package.json
Opening this PR as a potential fix to #2199.
**Original issue**: 
Latex equations do not render correctly:
Initially I thought it was a syntax issue with the LaTex in the .md file but after many unsuccessful attempts I concluded that LaTex/KaTex is just not supported in the docs, yet. (it doesn't seem commonly used across the docs site in any case which is why we didn't pick it up). 
**Changes made**:
I added in the plugins required for KaTex rendering as per the docusaurus documentation for version 2:
[docusuarus version 2 - adding math support](https://docusaurus.io/docs/2.x/markdown-features/math-equations)
**Result**:
LaTex now renders correctly:
=> Fix for broken LaTex rendering

docs/en/guides/creating-tables.md, docs/en/guides/developer/deduplication.md
The old training courses were deprecated and new training modules were released as part of the ClickHouse Developer course. This PR updates all training links (total of four) in the docs to the new modules.
=> Update old training links

docusaurus.config.js
Doc Check in https://github.com/ClickHouse/ClickHouse/pull/63260 complains about missing redirects ...
=> Add a redirect from `invertedindexes` to `fulltextindexes`

docusaurus.config.js
Reverts ClickHouse/clickhouse-docs#2277
Doesn't work, breaks https://github.com/ClickHouse/ClickHouse/pull/63260 over and over and over.
=> Revert "Add a redirect from `invertedindexes` to `fulltextindexes`"

README.md
Removes need to add Debian package repository for `yarn`. Bug found by @rschu1ze.
=> Specify use npm install --global to instal yarn

docs/en/cloud/security/aws-privatelink.md, docs/en/cloud/security/gcp-private-service-connect.md
Update documents: fail if some of env vars are not set.
using ${var_name:?} approach will error if env var is not set:
```
TEST_VAR=test
echo ${TEST_VAR:?}
test
unset TEST_VAR
echo ${TEST_VAR:?}
-bash: TEST_VAR: parameter null or not set
```
=> [AWS/GCP] PL / PSC docs improvement

docs/en/integrations/data-ingestion/clickpipes/kinesis.md
Closes #2321 and adds note on setting up IAM role/credentials at the top of the document to avoid user error.
=> ClickPipes Kinesis: add note on IAM roles/credentials

docs/en/integrations/language-clients/js.md
Added docs for the `auth` (https://github.com/ClickHouse/clickhouse-js/pull/279) and `session_id` (https://github.com/ClickHouse/clickhouse-js/pull/281) overrides. Reorganized the `BaseQueryParams` part a little bit. A link to the repository was added in the intro.
=> Update the CHJS docs for 1.1.0

docs/en/integrations/data-ingestion/clickpipes/secure-kinesis.md
ListStreams unfortunately does not work without a `*` on the streams ([aws docs](https://docs.aws.amazon.com/streams/latest/dev/controlling-access.html#kinesis-using-iam-examples)). Adding this to our iam policy docs to avoid future confusion for customers.
=> Update kinesis secure role setup to include ListStreams as a separate section of the policy with an allow all

docs/en/integrations/data-ingestion/clickpipes/kafka.md, docs/en/integrations/data-ingestion/clickpipes/kinesis.md, docs/en/integrations/data-ingestion/clickpipes/object-storage.md
The main change is adding a note for `Full Access` being required for Materialized Views.
While I was at it, I noticed a few small things that wanted to improve along the way:
- More consistent capitalization
- Fix section headers for Authentication section on object stores
- Fix Permissions section styling, from codeblock to list.
Before:
After:
=> Update permissions docs for Object Store ClickPipes

docs/en/chdb/index.md
- Adds the link to Auxten's blog which was previously not linked.
- Updates the link of `Official ClickHouse Blog` which was pointing to Auxten's blog,
=> Link updates for chDB

docs/en/guides/developer/alternative-query-languages.md
Changes:
- Added `kusto` to the alternative query languages page, with example
- Updated page overall to clarify that these languages are experimental
=> Update alternative query languages page to include Kusto

docs/en/get-started/query-endpoints.md
As of today, only a user with an Admin Console Role is entitled to create a query API endpoint.
=> Query API Endpoints - Admin Console Role

docs/en/integrations/data-ingestion/clickpipes/object-storage.md
TSV format is not yet supported.
Enhancement tracked here: https://github.com/ClickHouse/clickpipes-platform/issues/1438
=> TSV not yet supported

docs/en/integrations/data-ingestion/clickpipes/object-storage.md, docs/en/integrations/data-ingestion/s3/index.md
Virtual columns are supported in ClickPipes, so added a callout about this with a link to the list of virtual columns.
S3 Integration already mentioned it, but this adds a link to the page so it's more discoverable what virtual columns are available.
=> Add note about S3 virtual columns for clickpipes and integrations

docs/en/tutorial.md
Hello !
```
SELECT
count(1) AS total,
dictGetOrDefault('taxi_zone_dictionary','Borough', toUInt64(pickup_nyct2010_gid), 'Unknown') AS borough_name
FROM trips
WHERE dropoff_nyct2010_gid = 132 OR dropoff_nyct2010_gid = 138
GROUP BY borough_name
ORDER BY total DESC
```
From this query, in the `docs/en/tutorial.md` file, at "4. Create a Dictionary" step 7,  the current docs state ```The result looks like the following, and notice there are quite a few trips where the *dropoff* neighborhood is unknown``` instead of, I think, ```The result looks like the following, and notice there are quite a few trips where the *pickup* neighborhood is unknown```,
As we already know the dropoff which are either `dropoff_nyct2010_gid = 132` or `dropoff_nyct2010_gid = 138` and we're looking at the pickup …
=> fix-docs/en/tutorial.md_4.-Create-a-Dictionary/7.-'dropoff'-to-'pickup'

docs/en/integrations/language-clients/java/index.md
While approaching using the client for the first time, I encountered a few things that took me a while to sort out, so I wanted to contribute to the docs so it might be more clear. 
I also came across other related issues where others discuss these same issues: 
* https://github.com/ClickHouse/clickhouse-java/issues/1510
* https://github.com/ClickHouse/clickhouse-java/issues/1317
What I changed in this PR:
* I added another example for how to connect to a cluster with a single node using a connection string that doesn't include the `jdbc:ch` prefix. I had originally tried copying the example code with that included and got all kinds of errors with using the `jdbc:ch:http://server1.domain` format. I am not sure if the original code is correct or not, but if someone can help me confirm i …
=> Update the java client documentation

docs/en/integrations/data-ingestion/clickpipes/kafka.md
Documents that "bare" schema registry urls will now work.
=> Update ClickPipes schema registry options

docs/en/integrations/data-ingestion/clickpipes/object-storage.md
Add a note about modifications to destination table and materialized views.
In addition, remove FAQ about continuous ingest as it's already available.
=> Update clickpipes object storage limitations

docs/en/integrations/data-ingestion/clickpipes/index.md
This changes the status of clickpipes object ingest from beta to stable for the upcoming GA launch (also updates kinesis)
This relates to https://github.com/ClickHouse/clickpipes-platform/issues/2540
=> Change clickpipes object ingest from beta to stable for launch

docs/en/integrations/data-ingestion/etl-tools/airbyte-and-clickhouse.md
The "note" should not be before the header because it messes up the page title. This fixes it.
=> Fix heading of airbyte-and-clickhouse.md page

src/theme/Admonition/index.js
Change capitalization of default admonition titles
=> Change capitalization of default admonition titles

sidebars.js
Add release notes section for cloud
=> Add release notes section for cloud

docs/en/cloud/security/cloud-access-management.md
`sql_console_role:...` doesn't work, it should be `sql-console-role:...`.
=> Fix spelling of custom SQL console roles

knowledgebase/mapping-of-system-metrics-to-prometheus-metrics.md
This knowledge base entry provides a mapping table for metrics used in system.dashboards to Prometheus metrics in system.custom_metrics.
=> Mapping of metrics in system.dashboards to Prometheus metrics in system.custom_metrics

docs/en/guides/developer/deduplicating-inserts-on-retries.md
Reverts ClickHouse/clickhouse-docs#2500
Original PR https://github.com/ClickHouse/clickhouse-docs/pull/2394
The code has been committed, so the doc has to be restored.
https://github.com/ClickHouse/ClickHouse/pull/66144
=> Revert "Temporarily remove deduplicating inserts on retries"

docs/en/integrations/data-ingestion/gcs/index.md
Add note about GCS for cloud only on integrations page
=> Add note about GCS for cloud only on integrations page

docs/en/chdb/install/python.md
=> [Docs] Fix python install chdb misspell

docs/en/guides/sre/configuring-ssl.md, docs/en/guides/sre/user-management/ssl-user-auth.md
1. `-CAcreateserial` isn't recommended by OpenSSL docs anymore:
```If the -CA option is specified and neither <-CAserial> or <-CAcreateserial> is given and the default serial number file does not exist, a random number is generated; this is the recommended practice.```
2. Need to specify `-copy_extensions copy` otherwise the `subjectAltName` in the CSR isn't added to the certificate.
=> minor fixes to documentation around setting up TLS

docs/en/guides/best-practices/sparse-primary-indexes.md
Inspecting the primary index file (an optional part of this guide) only works if it's not compressed. Compression was enabled by default in https://github.com/ClickHouse/ClickHouse/pull/42587, so these instructions currently don't work easily.
To "fix" this we could:
1. **Either:** Disable `compress_primary_key` on the relevant DDL queries. This PR proposes this approach.
2. **Or:** Include a note in the expandable optional instructions "Inspecting the content of the primary index", explaining that for these instructions to work, the tables will need to be recreated with `compress_primary_key = 0`. I'm open to this (and it's not too hard) but thought it might be more cumbersome for readers.
Or perhaps there is a way to modify the instructions to inspect the primary index file to …
=> Disable compress_primary_key in the sparse primary indexes introduction

docs/en/guides/best-practices/sparse-primary-indexes.md
Fix grammar in `### Option 2: Materialized Views` section
=> Update sparse-primary-indexes.md "Option 2: Materialized Views" section

docs/en/cloud/security/saml-sso-setup.md
This corrects the direct link url for multi-org SSO setup per this case:
https://clickhouse.lightning.force.com/lightning/r/Case/500Uy00000GP2f1IAD/view
=> Corrects direct link url for multi-org SSO.

docs/en/integrations/data-ingestion/clickpipes/kafka.md
This adds a quick blurb describing custom certificates for Kafka ClickPipes
=> Add blurb for custom certificates for kafka clickpipes

docs/en/integrations/language-clients/js.md, docs/index.md
Changes the JS client slug from `/en/integrations/language-clients/javascript` to just `/en/integrations/javascript`, bumps versions in a few places.
=> Update CHJS docs, change the CHJS slug

plugins/header.js
Update default GitHub star count in case of failed rate limits
=> Update default GitHub star count

docs/en/cloud/reference/cloud-compatibility.md
Fix incorrect categorization as database engines
=> Fix incorrect categorization as database engines

docs/en/use-cases/observability/integrating-opentelemetry.md
Fix indentation in otel-collector example config.yaml files
For example:
```
receivers:
filelog:
...
```
needs to be
```
receivers:
filelog:
...
```
=> Fix YAML indentation in integrating-opentelemetry.md

docs/en/integrations/language-clients/rust.md
Fixed Geo types docs and added a link to the new example.
To be merged after https://github.com/ClickHouse/clickhouse-rs/pull/147
=> Update Geo info in the Rust client docs

docs/en/integrations/data-ingestion/clickpipes/object-storage.md
=> Update clickpipes object storage file size limit

docs/en/about-us/adopters.md
Update adopters, adding Canopus Networks, CipherStash, Gumlet, and INCREFF meetup presentations.
=> Update adopters.md with meetup presentations

docs/en/cloud/reference/byoc.md
Remove inaccurate description of adding a user-defined metrics for BYOC deployments.
=> Remove "adding metrics" section from BYOC reference

docs/en/integrations/data-ingestion/clickpipes/object-storage.md
The mention of "Full access" permissions needed for materialized views is a bit hidden under the whole setup instructions with screenshots and is very easy to miss.
This adds a note under "Materialized Views" section to be explicit about the permissions needed, or a workaround with roles.
=> More explicit mention about object storage pipes and MVs

docs/en/integrations/language-clients/python/index.md
Remove leading zero when creating datetime, which caused SyntaxError
=> fix syntax error in python client docs

docs/en/integrations/language-clients/python/index.md
Small clarification re Python client Variant type support.
=> Minor updates for clickhouse-connect 0.8.2 release

docs/en/cloud/changelogs/changelog-24-6.md, docs/en/cloud/changelogs/changelog-24-8.md, sidebars.js
Add cloud changelog for Release 24.8
=> Add cloud changelog for Release 24.8

docs/en/integrations/prometheus.md
There are 1410 `TYPE Clickhouse` matches in my endpoint's output, which would make it 4230 custom metrics which could end up costing some $200 a month or more.  It seems wise to alert people to this, so they can decide for themselves whether it is worth it.
=> Warn about Datadog Custom Metrics

docs/en/whats-new/changelog/2022.md
A faulty systemd service comment may cause upgrade issues on some Linux distributions, where the `/run/systemd` directory permissions are changed to the `clickhouse` user and group, causing all systemd operations to fail after upgrade.
See: https://github.com/ClickHouse/ClickHouse/issues/65862
=> docs: Add a warning for users upgrading to 22.12

sidebars.js
Remove MySQL binlog settings in sidebars
=> Remove MySQL binlog settings in sidebars

docs/en/cloud/bestpractices/asyncinserts.md
=> Fix async_insert link

sidebars.js
=> Remove duplicate sidebar link

docs/en/integrations/data-ingestion/clickpipes/index.md
Remove unnecessary ClickPipes FAQ question. There's a table above in the page that already shows the supported data sources.
=> Remove unnecessary ClickPipes FAQ question

docs/en/cloud/manage/openapi.md
This adds a note to the Managing API Keys page to clarify what permissions the `developer` and `admin` API roles have.
A customer wanted clarification on this.
`/en/cloud/manage/openapi`
=> Add note on API permission scope.

docs/en/integrations/data-ingestion/etl-tools/dbt/index.md
The `dbt` doc is getting bigger, so I added this TOC to make it easier for users to navigate and consume.
Any heading above 2 on the page will be added automatically.
=> add table-of-content to dbt docs

docs/en/integrations/data-ingestion/apache-spark/index.md
This PR adds code examples in 4 different APIs (Java, Scala, Python, and SQL) to the Spark JDBC section.
In addition, a table of contents was added to the top of the doc, and a few heading mismatches were addressed.
=> Enhance Spark JDBC examples

docs/en/cloud/manage/sticky-endpoints.md
Add private preview label for sticky endpoints
=> Add private preview label for sticky endpoints

docs/en/cloud/security/aws-privatelink.md
The AWS PrivateLink doc page links to a Terraform example and that page no longer exists. I have updated the link.
=> Fixes link to PrivateLink Terraform example.

docs/en/integrations/data-ingestion/clickpipes/kinesis.md
Updates ClickPipes docs to add  `_sequence_number` as supported Kinesis virtual column
=> Add _sequence_number as supported Kinesis virtual column

docs/en/integrations/language-clients/js.md
Update the docs with the new functionality added in https://github.com/ClickHouse/clickhouse-js/pull/328
=> Update the JS docs for 1.8.0

docs/en/guides/sre/keeper/index.md
=> Add Prometheus docs to Keeper

knowledgebase/outputSendLogsLevelTracesToFile.md
A knowledge base document showing how to output send_logs_level traces to file using clickhouse-client.
=> KB to output send_logs_level traces to file using clickhouse-client

docs/en/data-compression/compression-in-clickhouse.md
- Fixes some formatting issues in SQL examples such as:
- Makes the list of compression codecs a table for better readability.
Before:
After:
=> Update formatting for `Compression in ClickHouse` page

docs/en/guides/inserting-data.md
Makes a number of changes to the [Inserting Data](https://clickhouse.com/docs/en/guides/inserting-data) starter guide.
- Fixes typos.
- Separates out text into paragraphs for easier readability.
- Rephrases some sentences for easier understanding.
- Formats page for easier readability.
- Update the basic example to show the result.
- Adds links in a number of places.
=> Improvments to `Insert Data` starter guide

docusaurus.config.js, src/theme/Admonition/index.js
Adds two new admonitions: `experimental` and `obsolete` as a way to standardise the way we communicate to users which features are experimental or obsolete. 
The new admonitions can be used as:
```
:::experimental
This database engine is experimental. To use it, set `allow_experimental_database_materialized_postgresql` to `1` in your configuration files or by using the `SET` command:
:::
```
Renders:
```
:::obsolete
This database engine is obsolete and can no longer be used.
:::
```
Renders:
Currently we just use the `info` admonitions for these (see [here](https://clickhouse.com/docs/en/engines/database-engines/materialized-postgresql) and [here](http://localhost:3000/docs/en/engines/database-engines/materialized-mysql))
=> Admonitions for `experimental` and `obsolete`

docs/en/integrations/data-visualization/mitzu-and-clickhouse.md, docusaurus.config.js, src/theme/Navbar/Content/index.js
Cleans up mitzu docs, fixes nav bar and the admonions cc @Blargian
=> Mitzu refine

sidebars.js, src/components/DocsCategoryMobileNav/Hamburger.jsx, src/components/DocsCategoryMobileNav/HamburgerMenu.jsx, src/components/DocsCategoryMobileNav/MobileMenu.jsx, src/components/DocsCategoryMobileNav/styles.module.css, src/theme/Navbar/Content/index.js, src/theme/Navbar/Content/styles.module.css, src/theme/badges/CloudAvailableBadge/index.js
I'm sure there are very few people looking at ClickHouse docs on mobile... never the less, the secondary (docs) navigation bar looks horrible on mobile:
This PR adds custom React components `Hamburger`, `HamburgerMenu` and `MobileMenu` (grouped under `DocsCategoryMobileNav`) such that the secondary menu acts in a similar way to the primary menu (displays a burger menu and navigation overlay for smaller screen sizes).
**Result**
Still to do:
=> Fix ugly looking navigation on mobile

docs/en/guides/sre/user-management/index.md
=> Fixed incorrect links to headers of Settings Profiles management queries

docs/en/materialized-view/refreshable-materialized-view.md
This adds a cross reference on how to manage DEPENDS on for refreshable-materialized-view
The page [refreshable-materialized-view](https://clickhouse.com/docs/en/materialized-view/refreshable-materialized-view) where materialized views are explained, mentions Dependancies but it does not link you to the docs in terms of how these are set.
=> docs: Update refreshable-materialized-view.md to cross reference DEPENDS ON

docs/en/integrations/clickhouse-client-local.md
=> chore: fix error link

src/theme/Details/styles.module.css
Fixes https://github.com/ClickHouse/clickhouse-docs/issues/2861
=> fix rendering for light mode on details table

docs/en/cloud/manage/upgrades.md
"Fast Release" is only available for the production tier and is a self-serve process accessible through the UI. Rewording this as the previous message may cause ambiguity for customers using the development tier, where the UI does not support the Fast Release option.
=> fast release is now self-serve for production tier

docs/en/integrations/data-ingestion/clickpipes/object-storage.md
- Adds a introductory paragraph
- Adds a section on exactly-once semantics and view support
=> Updates Object Storage ClickPipe docs

src/theme/Admonition/styles.module.css
Fix the overflow of Admonitions https://github.com/ClickHouse/clickhouse-docs/issues/1897
=> fix overflow of Admonition content

docs/en/integrations/data-ingestion/etl-tools/apache-beam.md
Due to multiple fixes in our `ClickHouseIO` connector ( apache/beam#32229 and apache/beam#32100), we recommend using Apache Beam version `2.59.0` (earlier versions may not fully support the connector's functionality).
=> Update the recommended beam version

docs/en/materialized-view/refreshable-materialized-view.md
I believe refreshable views are not experimental any more based on: https://github.com/ClickHouse/ClickHouse/pull/70550
Thus there shouldn't be any need to set this before creating them.
=> Refreshable views are no longer experimental

docs/en/guides/developer/deduplicating-inserts-on-retries.md
=> improve de-dupe docs

sidebars.js, src/theme/Navbar/Content/index.js
Link was wrong. bumping sparse indices guide as its the most important.
=> fix menu for perf and optimizations

docs/en/faq/integration/index.md, docs/en/integrations/data-ingestion/dbms/postgresql/connecting-to-postgresql.md, docs/en/integrations/data-sources/postgres.md, sidebars.js
Avoids switching between menus when reading postgres guide. File org on disk is still a mess.
=> fix postgresql linking

plugins/header.js
There's a production level issue that needs fixing asap. When going from ClickHouse.com to docs, we're getting the following error `TypeError: Cannot read properties of undefined (reading 'stars')`.
I cannot reproduce in any other environment, but in theory this PR should protect against this error by first defining a value for stars before everything else loads.
=> Defining stars value up front and adding fallback

docs/en/guides/best-practices/sparse-primary-indexes.md, docs/en/integrations/data-ingestion/dbms/mysql/index.md, docs/en/integrations/data-sources/mysql.md, docs/en/managing-data/core-concepts/parts.md, docs/en/managing-data/delete_mutations.md, docs/en/managing-data/drop_partition.md, docs/en/managing-data/truncate.md, docs/en/managing-data/update_mutations.md, docs/en/optimize/index.md, sidebars.js, src/theme/Navbar/Content/index.js
Adds pages to avoid switching between menus which is both jarring and hard to follow.
Added @tom-clickhouse guide on parts under a new core concepts section.
This is imperfect, we need better dedicated pages vs just importing reference documentation in some places. But progress is more important.
=> ensure no page switching + add core concepts

docs/en/integrations/data-ingestion/clickpipes/postgres/source/rds.md
Some users have their RDS behind an [RDS proxy](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html) pooler. RDS Proxy does not support streaming replication protocols and thereby the Postgres ClickPipe.
This PR adds some information on workarounds for this in RDS doc
=> Postgres ClickPipe: Add section for rds proxy

docs/en/integrations/language-clients/js.md
Formatting fixes to [`/docs/en/integrations/javascript`](https://clickhouse.com/docs/en/integrations/javascript)
- Tabulate the config settings lists
- Add experimental badges
- Use correct syntax for footnotes
- Fix a heading which is the wrong size
=> Improve formatting of `/en/integrations/javascript`

docusaurus.config.js
Closes #2980. Adds a redirect to a broken link which is linked from developer on-demand training slides.
=> update developer on-demand training broken link

docs/en/cloud/manage/scaling.md
Adds comment regarding automatic idling behaviour with refreshable materialised views and S3 queue. Closes https://github.com/ClickHouse/clickhouse-docs/issues/3041
=> Add description of how automatical idling works with RMV and S3 Queue

docs/en/integrations/data-ingestion/clickpipes/object-storage.md
A cloud user was having issues with the GCS pipe - although the bucket was public and we could read objects, we couldn't list bucket pattern contents which is a critical part of how the pipe functions.
=> [ClickPipes] Add GCS FAQ for public buckets

knowledgebase/mysql-to-parquet-csv-json.md
The code snippet in `mysql-to-parquet-csv-json.md` seems to contain a typo. This PR fixes it.
=> Fix a typo in code snippet

docs/en/cloud/manage/backups.md
Updates [this section](https://clickhouse.com/docs/en/cloud/manage/backups#undeleting-or-undropping-tables) with the correct information. We no longer need support for dropping large tables.
Closes https://github.com/ClickHouse/clickhouse-docs/issues/3051
=> update restrictions to contact support for table drops greater than 1TB

package.json, yarn.lock
upgrade to docusaurus 2.4.3. Need to do before we can go to v3.
=> upgrade to docusaurus 2.4.3

src/theme/SearchBar/index.js
It seems like we are importing an API that is no longer exported from the docusaurus package. I believe I've found a new hook that serves the same purpose.
Fixes https://github.com/mwoenker/clickhouse-docs/pull/new/mw-fix-search-crash
=> Use new search link APi

copyClickhouseRepoDocs.sh
Closes #3047. 
There are currently no new releases for 2025 so the changelog shows as blank.
I have updated the script to reference the previous years change log if this happens.
=> update changelog to reference previous year if blank

docs/en/integrations/language-clients/js.md
Removes super script references which register as broken links in htmltest.
=> Remove super script references which register as broken links in htmltest

package.json, yarn.lock
addresses https://github.com/ClickHouse/clickhouse-docs/pull/2725
=> update http-proxy-middleware from 2.0.6 to 2.0.7

docs/en/cloud/bestpractices/avoidoptimizefinal.md
Small formatting and language edits to Avoid Optimize Final page.
=> Docs: formatting and language edit to Avoid Optimize Final page

docs/en/whats-new/roadmap.md
Adding the link to the 2025 roadmap.
Adding the link to the [2025](https://github.com/ClickHouse/ClickHouse/issues/74046) roadmap.
=> Roadmap update

docs/en/guides/developer/lightweight-update.md, docs/en/managing-data/updating-data/overview.md
This feature was moved to open source recently: https://github.com/ClickHouse/ClickHouse/pull/74877.
=> Remove cloud badge from lightweight updates

copyClickhouseRepoDocs.sh
Fixes Changelog generation script which was not functioning correctly after it was changed to display a note if no changelog is present yet at the start of a new year.
=> Fix Changelog generation script

scripts/table-of-contents-generator/toc_gen.py
If you try to generate a table of contents file containing dates, the script throws error:
```
TypeError: Object of type date is not JSON serializable
```
Adds `default=str` to `json.dumps` method such that dates will be written as strings. For our purposes this is probably sufficient for now.
=> Serialise dates to strings for table of contents generator JSON dump

docs/en/cloud/security/index.md
=> Fix broken links on cloud/security landing page

docs/en/cloud/manage/jan2025_faq/dimensions.md
Fixed replica size for the ClickPipes example
=> Fixed replica size for the ClickPipes example

docs/en/cloud/bestpractices/usagelimits.md
We will return these lines on rollout.
=> Temporary removing limits for tables and databases - they are not yet implemented

docusaurus.config.js
The links to `Primary Key Indexes` is missing a redirect now that it's in the guides section.
For example: https://clickhouse.com/docs/en/concepts/why-clickhouse-is-so-fast#storage-layer-data-pruning
=> Fix links to primary key guide

scripts/knowledgebase-checker/knowledgebase_article_checker.py
Error messages when the KB article fails are rather vague.
Makes a change to specifically output what the issue is and which KB article it is complaining about.
=> KB article checker: Improve error messages on KB checker

docs/en/integrations/data-ingestion/dbms/postgresql/rewriting-postgres-queries.md
The Postgres query had 10 even if the results only shows 5 results, which corresponds to the re-written Clickhouse query.
Quick typo fix.
=> Fix Typo in the Postgres Query (Limit)

src/css/custom.scss, src/theme/DocSidebar/Desktop/Content/index.js, src/theme/DocSidebar/Desktop/index.js
Try to fix scroll position of main content when left sidebar requires scrolling to show active item
Also now the search bar is always visible, previously search bar and the first item from the sidebar was hidden after scrolling the main content.
You can see both issues on https://clickhouse.com/docs/en/optimize/skipping-indexes
I made minimum amount of changes which fixed described issues.
I tested:
1. Scrolling the left sidebar menu to active item works correctly - https://clickhouse.com/docs/en/optimize/skipping-indexes
1. Scrolling to headings works correctly - https://clickhouse.com/docs/en/sql-reference/functions/string-functions#trim
https://github.com/user-attachments/assets/84cad7d3-0754-4845-bfc6-e1a7fc165470
https://github.com/user-attachments/assets/38acca53-9207-494a-8b84-c8b67 …
=> Fix scroll position of main content when left sidebar requires scrolling to show active item

docs/en/cloud/get-started/query-endpoints.md
=> Remove beta badge from query API endpoints

src/theme/Navbar/Content/index.js
=> Correct Core Concepts link redirecting to wrong place in the docs

docs/en/integrations/data-ingestion/data-formats/json/other.md
Resolves issue with Markdown syntax.
=> Fix Markdown syntax in docs/en/integrations/data-ingestion/data-formats/json/other.md

src/components/DocsCategoryDropdown/styles.module.css
Fixes menu which has yellow items permanently:
- items are white in dark mode, black in dark mode
- in dark mode on hover the title turns yellow
=> Improve menu styling

docs/en/cloud/manage/billing.md
Reverts ClickHouse/clickhouse-docs#3227
LaTex renders okay in some browsers but seems to show double in others:
Reverting the change and I will modify the table items not to use LaTex until I figure out what the issue is.
=> Revert "Update billing page"

docs/en/integrations/data-ingestion/clickpipes/postgres/faq.md, knowledgebase/aws-privatelink-setup-for-clickpipes.mdx
=> refactor(clickpipes): rds private link docs

docs/en/cloud/security/cmek.md, scripts/aspell-ignore/en/aspell-dict.txt
Add description for GCP TDE feature. https://docs.google.com/document/d/1AC99omttt6VaggjziakVU5V1QcjdndgT-4OuiA7n5kE/edit?tab=t.0#heading=h.8da6yfm96kpe
=> Add CMEK instructions for GCP

scripts/search/index_pages.py
iframes and divs show in search drop down. We should probably remove all html from the markdown - ill follow up.
=> fix html in search

docs/en/integrations/data-ingestion/clickpipes/postgres/index.md
Need to link to this details section for a blogpost but it's not possible to link to a header within a details section.
=> add header for advanced settings

scripts/copy-clickhouse-repo-docs.sh
- Needed for edge case where you make a change on main repo but the docs check fails because the copy-script is pulling from master instead of using the changes from the current branch.
=> Build scripts: don't pull repo if CI environment variable is true

docs/en/migrations/postgres/designing-schemas.md
=> Docs: Fix code blocks designing-schemas.md

docs/en/managing-data/core-concepts/merges.md, docs/en/managing-data/core-concepts/partitions.md, docs/en/managing-data/core-concepts/parts.md, src/css/custom.scss
As discussed with Tom, we make images 60% width on desktop however this displays them too small on mobile. See [Example](https://clickhouse.com/docs/en/merges)
- Added a media query to force images on mobile to 100% width.
=> Make images 100% width on mobile

vercel.json
Adds redirect,
from: https://clickhouse.com/docs/manage/billing#faqs
to: https://clickhouse.com/docs/cloud/manage/billing/overview#faqs
=> Add redirect for billing FAQ

vercel.json
=> add redirect for quick start from pricing page

scripts/settings/autogenerate-settings.sh
Removes /en from autogenerated slug
=> remove /en

package.json, yarn.lock
Reverts ClickHouse/clickhouse-docs#3320
Seems to cause fail of docs check: 
```
From https://github.com/ClickHouse/clickhouse-docs
a3a0f2b9..ec97b3c4  main       -> origin/main
Updating a3a0f2b9..ec97b3c4
error: Your local changes to the following files would be overwritten by merge:
yarn.lock
Please commit your changes or stash them before you merge
```
=> Revert "Bump esbuild-loader from 4.2.2 to 4.3.0"

docusaurus.config.js, vercel.json
- Fixes redirects for 404s 
- Fixes the "edit this page" redirect which broke
=> Redirects for 404s

.github/workflows/check-build.yml
Reverts ClickHouse/clickhouse-docs#3318
Yarn.lock conflict causing issue in https://github.com/ClickHouse/ClickHouse/pull/76639
=> Revert "Bump actions/github-script from 6 to 7"

scripts/.markdownlint-cli2.yaml, scripts/markdownlint/rules/headings_have_custom_anchors.js
- Modifies the custom rule which enforces unique anchor headings to also check that anchors are unique per page
=> Markdown-lint: modify `custom-anchor-headings` rule to also check for uniqueness

docs/integrations/data-ingestion/s3/index.md
=> update s3 guide with describe

docs/data-compression/compression-in-clickhouse.md
A simple formatting fix of [Compression in ClickHouse | ClickHouse Docs](https://clickhouse.com/docs/data-compression/compression-in-clickhouse)
* nothing applies
-  [x] URL changes should add a redirect to the old URL via https://github.com/ClickHouse/clickhouse-docs/blob/main/docusaurus.config.js
=> docs: fix table formatting

scripts/settings/autogenerate-settings.sh
Autogenerated table for settings is missing a description for settings pages which are autogenerated. (Missing in the autogen script)
=> Update autogenerate-settings.sh with descriptions

docs/cloud/manage/api/api-overview.md
=> Fix link to swagger

docs/cloud/manage/api/api-reference-index.md, docs/cloud/manage/api/usageCost-api-reference.md, sidebars.js
usageCost page was floating. Adds it to the sidebar and index page.
=> give usageCost page a sidebar

src/components/BlogBreadcrumbs/BlogBreadcrumbs.js
Fix for styling issue on paginated pages (from the second page onwards):
=> fix knowledgebase page

clickhouseapi.js
Our markdown generation for API response payloads returns incomplete tables and response payloads for any response that has nested fields.  
A few examples—
https://clickhouse.com/docs/cloud/manage/api/keys-api-reference
Current result:
Expected result:
| Name | Type | Description |
| :--- | :--- | :---------- |
| key.id | uuid | Unique API key ID. | 
| key.name | string | Name of the key | 
| key.state | string | State of the key: 'enabled', 'disabled'. | 
| key.roles | array | List of roles assigned to the key. Contains at least 1 element. | 
| key.keySuffix | string | Last 4 letters of the key. | 
| key.createdAt | date-time | Timestamp the key was created. ISO-8601. | 
| key.expireAt | date-time | Timestamp the key expires. If not present or is empty the key never expires. ISO-8601. | …
=> Fix nested fields expression in api reference docs pages

docs/integrations/data-ingestion/clickpipes/postgres/source/supabase.md
=> Remove nested danger tags

docs/about-us/adopters.md
- Adds Huawei to list of adopters for their HUAWEI cloud stack offering. ClickHouse features heavily in the documentation.
- Adds Nvidia to list of adopters. ClickHouse is mentioned in the documentation for NVIDIA AI Aerial.
=> Update adopters.md with Huawei, Nvidia

docs/cloud/manage/jan2025_faq/plan_migrations.md
It seems that we no longer offer Dedicated services, and I believe the intention was to support users who need to migrate from Dedicated to a new plan.
=> Rewording migration guidance from dedicated to new plan

docs/cloud/changelogs/changelog-24-12.md, docs/managing-data/core-concepts/shards.md
We merged the PR which enables checking for issues with explicit anchor tags only after merging PRs which fail this check, so they got through without being picked up.
Fixes docs check.
=> Fixes to docs check failing on explicit anchors

docs/cloud/reference/architecture.md
Image is an svg, not a png so usage of `src` is invalid.
=> Fix docs check

docs/guides/developer/alternative-query-languages.md
Fixes incorrect anchor level usage
=> Fix anchor levels

docs/integrations/data-ingestion/clickpipes/postgres/faq.md
Adds detailed instructions for handling tables without primary keys and SQL examples
=> docs: enhance Postgres publication setup guidance

docs/cloud/security/saml-sso-setup.md
#3431 
- Add Duo SAML setup instructions
- Correct formatting of direct link (https://console.clickhouse.cloud/?connection={organizationID})
=> #3431 saml update

scripts/settings/autogenerate-settings.sh, scripts/table-of-contents-generator/toc_gen.py
- Hides the curl download progress and query output when autogenerate script runs for cleaner build logging
- removes `/docs` from autogenerated table of contents tables (needed for translations)
=> Script improvements

docusaurus.config.jp.js, i18n/jp/docusaurus-plugin-content-docs/current/about-us/distinctive-features.md, i18n/jp/docusaurus-plugin-content-docs/current/cloud/reference/byoc.md, scripts/translate/translate.py, vercel.json
=> correct rewrites for translations

src/theme/BlogListPage/index.js, src/theme/BlogPostItem/index.js, src/theme/BlogTagsListPage/index.js, src/theme/BlogTagsPostsPage/index.js
Fixes a bug where the "Recent"/"Grouped by tags" navigation breaks after our i18n changes.
=> KB navigation: fix routing bug

plugins/floating-pages-exceptions.txt, sidebars.js
Adds page added in https://github.com/ClickHouse/ClickHouse/pull/78039 to sidebar
=> add userspace page cache to sidebar

.github/workflows/build-search.yml, scripts/copy-clickhouse-repo-docs.sh
We added something to `copy-clickhouse-repo-docs` a little while back such that the repo doesn't get pulled if `CI=true` in environment variables. In this case `CI=true` but we *do* want to pull the repo because this is not the docs-check image which does that already.
Could probably also set `CI=false` but i don't want to test how that affects github so have added a `-f` argument to `copy-clickhouse-repo-docs` which will do a "force pull", even if `CI=true`.
=> Fix search action

docs/cloud/security/compliance-overview.md
Fixes typo in the enterprise badge for PCI which currently reads "HIPAA is an enterprise tier feature..."
=> Fix: Enterprise badge for PCI says HIPAA

docs/integrations/data-ingestion/clickpipes/object-storage.md
Adds a small clarification to docs around IAM role creation.
=> Clarify role setup instructions for S3 ClickPipes

scripts/settings/autogenerate-settings.sh
=> show type and default for autogenerated server settings

docs/integrations/data-visualization/embeddable-and-clickhouse.md
Links went to a notion site - now to embeddable docs site
=> Update broken links

docs/integrations/data-ingestion/kafka/kafka-clickhouse-connect-sink.md
The configuration property was incorrectly mentioned as `topics2TableMap`. The correct property name is `topic2TableMap`. It wasn't very clear while setting up Kafka connectors that subscribed to multiple topics.
=> Fix typo in topics2TableMap to topic2TableMap in Kafka connect guide

docs/integrations/data-ingestion/clickpipes/mysql/index.md
This PR fixes two links in the overview page of MySQL ClickPipe - ones which point to MySQL RDS and MySQL Aurora guides. Currently they point to Postgres
=> MySQL Overview Doc: change links to point to mysql rds/aurora

docs/integrations/data-ingestion/clickpipes/mysql/source/aurora.md, docs/integrations/data-ingestion/clickpipes/mysql/source/rds.md
=> add missing replication permission for MySQL

docs/cloud/reference/supported-regions.md
Add new HIPAA/ PCI regions in AWS:
- eu-west-2
- eu-central-1
- us-east-2
=> Add new HIPAA and PCI regions

docs/integrations/data-ingestion/dbms/mysql/index.md, docs/integrations/data-ingestion/dbms/postgresql/connecting-to-postgresql.md
clean up Postgres data source a bit
add a call to action to MySQL data source linking to MySQL ClickPipe
=> refactor Postgres source slightly, link MySQL ClickPipe

docs/en/tutorial.md, scripts/aspell-dict-file.txt
Fixes #3268 
- Various style and grammar updates, including the following:
- Avoid ellipses ([reference](https://developers.google.com/style/ellipses))
- Hyphen vs. em dash ([reference](https://developers.google.com/style/dashes))
- Key-value, not “key -> value” ([reference](https://developers.google.com/style/word-list#key-value))
- Headings should be sentence case ([reference](https://developers.google.com/style/headings))
- Use the serial comma ([reference](https://developers.google.com/style/commas#serial-commas))
- Use parentheticals only when needed  ([reference](https://developers.google.com/style/parentheses))
- No exclamation points ([reference](https://developers.google.com/style/periods#exclamation-points))
- Use negation contractions …
=> Improvements to Advanced Tutorial doc 

docs/getting-started/example-datasets/amazon-reviews.md, docs/getting-started/playground.md, docusaurus.config.en.js
Adds a note on the Playground page with service specs.
=> Update playground.md with specifications

docs/guides/best-practices/query-parallelism.md
Reverts ClickHouse/clickhouse-docs#3639
@tom-clickhouse can we either not make runnable or drop static results bit. Static results makes  the live results redundant and vise versa - lets just use one or the other.
=> Revert "Made some of the queries runnable."

docs/managing-data/core-concepts/primary-indexes.md
Wait until we have a proper component to render static results as tabs.
=> Revert making some of the queries runnable.

docs/getting-started/example-datasets/nyc-taxi.md
=> Swap order of GCS and S3

src/components/CodeViewer/CodeInterpreter.tsx
=> fix wrap on buttons

docs/integrations/data-ingestion/data-formats/json/formats.md
https://github.com/ClickHouse/clickhouse-docs/issues/3621
=> JSONAsObject examples

docs/integrations/data-ingestion/clickpipes/aws-privatelink.md, knowledgebase/aws-privatelink-setup-for-clickpipes.mdx
=> feat(cdc-rpe): mention self served RPE guide instead

docs/integrations/data-ingestion/clickpipes/aws-privatelink.md, knowledgebase/aws-privatelink-setup-for-msk-clickpipes.mdx, static/knowledgebase_toc.json
This PR adds a knowledge base page for MSK multi-VPC setup for a ClickPipes reverse private endpoint.
=> Knowledge base for MSK multi-VPC setup for RPE

docs/migrations/postgres/appendix.md, i18n/ru/docusaurus-plugin-content-docs/current/integrations/data-ingestion/dbms/postgresql/data-type-mappings.md
Revert https://github.com/ClickHouse/clickhouse-docs/pull/3489 due to https://github.com/ClickHouse/ClickHouse/pull/79108
PostgreSQL's CHARACTER type stores number of characters, while ClickHouse's FixedString stores number of bytes. Thus, that 1:1 mapping doesn't work for all encodings. That's the reason it wasn't done for MySQL. Since those types mean different things, I think it's rather misleading to map one to the other. The safest option is to map CHARACTER types that mean characters to String instead.
e.g. there might be a Japanese word of 4 characters but that uses 18 bytes
=> Revert "Add FixedString to PostgreSQL mapping"

docs/cloud/reference/changelog.md
=> Cloud changelog: April 18

docs/integrations/data-ingestion/clickpipes/mysql/index.md, docs/integrations/data-ingestion/clickpipes/mysql/source/aurora.md, docs/integrations/data-ingestion/clickpipes/mysql/source/rds.md, docs/integrations/data-ingestion/clickpipes/mysql/source/rds_maria.md, scripts/aspell-dict-file.txt, sidebars.js
Basically RDS MySQL but without GTID mode setup being needed
Still working on MariaDB tile
Aurora MariaDB doesn't exist so not needed
=> [mysql] basic doc for RDS MariaDB

docs/cloud/bestpractices/usagelimits.md
A warehouse is a set of services that share the same data.  Today, the number of services in a warehouse is limited to 5.  This is a soft limit.
=> Documenting limit (soft) on number of services per warehouse

vercel.json
Adds redirects for two pages giving 404
=> Add redirects for recent 404s

docs/cloud/manage/billing/marketplace/overview.md
Added new  FAQ:
If my ClickHouse Organization is billed through a cloud marketplace committed spend agreement will I automatically move to PAYG billing when I run out of credits?
If your marketplace committed spend contract is active and you run out of credits we will automatically move your organization to PAYG billing. However, when your existing contract expires, you will need to link a new marketplace contract to your organization or move your organization to direct billing via credit card.
=> Added new FAQ for MP Committed Spend Billing

src/theme/DocItem/TOC/Desktop/index.js
=> banner change

docs/cloud/security/aws-privatelink.md
The org-level endpoints are deprecated in UI and OpenAPI. Endpoint can be attached directly to the service.
Related https://github.com/ClickHouse/control-plane/pull/15276
=> Private enpoints docs update: removed deprecated step

scripts/settings/session-settings.sql
Closes #3724. Adds logic to replace `auto(N)` which shows as `auto(4)` due to the number of threads used in the deploy machine. Default values with `auto()` will now be replaced with string `auto(N)`.
=> Settings: add logic to handle `auto(N)` default type

docs/data-compression/compression-in-clickhouse.md
Replace "out weighted" with "outweighed".
=> fix grammar in compression-in-clickhouse.md

src/theme/DocItem/TOC/Desktop/index.js
Added dynamic data fetching for the sidebar ad.
=> Add dynamic sidebar ad data fetching

docs/cloud/support.md
Two titles show on this page due to snippet import. Fix.
=> Fix double title

docs/guides/developer/alternative-query-languages.md
=> Fix broken link in `alternative-query-languages.md`

src/theme/Layout/index.js
This PR applies 0x0 dimensions to the scarf tracking pixel ensuring it doesn't add unwanted white space to the bottom of the page
=> Fixed scarf pixel displaying at 1x1 full width

knowledgebase/aws-privatelink-setup-for-clickpipes.mdx
`false` is not a valid value in Terraform. Fixes error:
Error: expected enforce_security_group_inbound_rules_on_private_link_traffic to be one of ["on" "off"], got false
=> Fix AWS Private Endpoint option value

plugins/remark-custom-blocks.js, src/components/Stepper/Stepper.tsx
VerticalStepper now supports:
```
<VerticalStepper headerLevel="h3">
</VerticalStepper>
```
=> Support using VerticalStepper with H3

knowledgebase/connection_timeout_remote_remoteSecure.mdx, knowledgebase/custom-dns-alias-for-instance.mdx, src/theme/BlogPostItem/index.js
New KB article on how to set up a custom DNS alias using a reverse proxy
=> KB: custom DNS alias for instance

docs/guides/best-practices/sparse-primary-indexes.md
```
× Module build failed:
╰─▶   × Error: MDX compilation failed for file "/Users/sstruw/Desktop/clickhouse-docs/i18n/zh/docusaurus-plugin-content-docs/current/guides/best-practices/sparse-primary-indexes.md"
│ Cause: Can't parse URL https://pastila.nl，并在[博客中介绍了 with base unspecified://
│ Details:
│ Error: Can't parse URL https://pastila.nl，并在[博客中介绍了 with base unspecified://
│     at parseURLOrPath (/Users/sstruw/Desktop/clickhouse-docs/node_modules/@docusaurus/utils/lib/urlUtils.js:162:15)
│     at parseLocalURLPath (/Users/sstruw/Desktop/clickhouse-docs/node_modules/@docusaurus/utils/lib/urlUtils.js:210:17)
│     at parseMarkdownLinkURLPath (/Users/sstruw/Desktop/clickhouse-docs/node_modules/@docusaurus/mdx-loader/lib/remark/resolveMarkdownLinks/index.js:12:51)
```
=> Fix link which breaks translations

docs/integrations/data-ingestion/clickpipes/object-storage.md
Something we noticed during testing, and update a limitation on materialized view detection.
=> Add limitation around clickpipes azure blob storage

docs/integrations/data-visualization/quicksight-and-clickhouse.md
=> Fix link which breaks docs translations

docs/integrations/data-ingestion/clickpipes/mysql/faq.md
need link for customers being notified their replication is broken due to invalidated binlog
=> mysql clickpipe: binlog faq

docs/cloud/manage/jan2025_faq/summary.md
=> Fix for part of doc which translations break on

docusaurus.config.en.js, docusaurus.config.jp.js, docusaurus.config.ru.js, docusaurus.config.zh.js
We were using a dark mode theme for light mode prism highlighting for some sad reason.
YAML syntax highlighting was looking pretty sad:
BEFORE:
AFTER:
=> Use a light mode theme for light mode

src/components/Feedback/index.jsx, src/components/Feedback/styles.module.scss, src/theme/DocItem/TOC/Desktop/index.js, src/theme/DocItem/TOC/Desktop/styles.module.scss
On system tables pages the sidebar is causing the page to be scrollable horizontally
https://clickhouse.com/docs/operations/system-tables/metrics
https://github.com/user-attachments/assets/fb4fd085-ed61-499a-b4cf-f8516bbdd694
=> Fix width issue

knowledgebase/aws-privatelink-setup-for-clickpipes.mdx
=> feat(rds-rpe): add cross-region step for endpoint service

docs/integrations/data-ingestion/clickpipes/mysql/source/aurora.md
Currently in the mysql aurora clickpipe doc we are using the screenshot from RDS for the parameter group. This PR fixes this
=> MySQL ClickPipe Aurora Doc: Fix screenshot for parameter group

docs/getting-started/install/install.mdx, src/lib/galaxy/galaxy.js, src/theme/DocItem/Layout/index.js, src/theme/DocItem/TOC/Desktop/index.js
Adds galaxy events to:
- Cloud sidebar advert
- Translation issue banner
- Cloud Callout on the install page
=> Add galaxy events to cloud advert and translation issue banner

docs/integrations/data-ingestion/data-formats/csv-tsv.md
Simple PR improves the grammar in one of the tips on the CSV format page.
=> improve grammar in csv header tip

docs/use-cases/observability/clickstack/deployment/local-mode-only.md, docs/use-cases/observability/clickstack/example-datasets/sample-data.md, docs/use-cases/observability/clickstack/getting-started.md
ClickStack: Fix local mode docs and demo data link
=> ClickStack: Fix local mode docs and demo data link

docs/integrations/data-ingestion/clickpipes/aws-privatelink.md
Add better docs for setting up ClickPipes with AWS PrivateLink using VPC Resource.
=> Add docs for AWS PrivateLink using VPC Resource

docs/data-modeling/projections.md
Updates the projections doc with the video by Mark
=> Update projections.md with video

docs/integrations/language-clients/js.md
Add an entry to the table of JS types for named tuples
=> add named tuple to js mapping table

src/theme/SearchBar/index.js
Current behavior is very annoying, so I decided to just fix this.
closes https://github.com/ClickHouse/clickhouse-docs/issues/3191, closes https://github.com/ClickHouse/clickhouse-docs/issues/3271
mp4 from https://github.com/ClickHouse/clickhouse-docs/issues/3191#issuecomment-2646572280 (this a bit old, now there are only two modals instead of three)
https://github.com/user-attachments/assets/a495c025-2174-48bf-b84a-3ef762e609bf
=> Fix showing two modals after pressing ctrl+k or / to open the search modal for the first time

docs/use-cases/data_lake/unity_catalog.md
Updating based on discussion here: https://clickhousedb.slack.com/archives/CU478UEQZ/p1750676732132329?thread_ts=1750676432.764169&cid=CU478UEQZ
=> Docs: Update unity_catalog.md to mention need to enable it via setting

docs/integrations/data-ingestion/clickpipes/aws-privatelink.md, docs/integrations/data-ingestion/clickpipes/index.md
- Refer supported AWS PrivateLink regions to a main page table
- Fix `us-east-2` as an "old" region for services running in newly provisioned ClickPipes regions
- Explicit mention available regions are AWS
=> Clarify AWS PrivateLink region support and IP whitelisting details

vercel.json
=> remove redirect

docs/integrations/data-ingestion/kafka/kafka-table-engine.md
There's a bigger update to the Kafka docs ongoing, but to remove the main source of confusion for users, let's just remove the badge ahead of that. Also for consistency with [`ClickHouse` #82746](https://github.com/ClickHouse/ClickHouse/pull/82746).
=> docs: remove Cloud not supported badge for the Kafka Table Engine

docs/cloud/security/compliance-overview.md, docs/cloud/security/setting-ip-filters.md
- Update compliance page to indicate PCI and HIPAA are available via self-service
- Update IP filters page with a note for services with 'Allow from anywhere' set that services may be periodically unidled by web scanners
=> Add PCI and HIPAA self-service and 'allow from anywhere' ip filter note

i18n/ru/docusaurus-plugin-content-docs/current/operations/settings/settings.md
CloudAvailableBadge becomes CloudOnlyBadge
=> CloudAvailableBadge -> CloudOnlyBadge

src/theme/CodeBlock/index.js
Fixes an edge case which causes a crash when a codeblock is empty
=> fix crash on empty code blocks

docs/guides/developer/lightweight-update.md, docs/managing-data/updating-data/overview.md
Changed lightweight update by on-fly mutations to avoid confusion.
=> Fix the documentation page to align with the new lightweight update page

src/theme/Admonition/index.js
The warning admonition shows "danger". Fix for this.
=> Fix warning admonition showing "danger"

src/components/RelatedBlogs/styles.module.scss
=> Styling: fix mobile styling of related blogs component

docs/integrations/data-ingestion/clickpipes/secure-kinesis.md
This fixes an issue where the kinesis IAM role was missing the permission to register and deregister the stream consumer for wildcard statements causing some consumers to not be able to [de]register their streams.
=> Add DeregisterStreamConsumer permission to blanket wildcard statement for kinesis iam setup process

docs/integrations/data-ingestion/clickpipes/mysql/faq.md
1. extending binlog retention period
2. configuring column to partition initial load
=> mysql faq: recommendations around initial load of large tables

docs/integrations/data-ingestion/clickpipes/mysql/source/generic_maria.md
https://mariadb.com/docs/server/ha-and-performance/standard-replication/replication-and-binary-log-system-variables#log_slave_updates
Off by default, whereas [log_replica_updates](https://dev.mysql.com/doc/refman/8.4/en/replication-options-binary-log.html#sysvar_log_replica_updates) is on by default for MySQL, so this issue hasn't come up there
=> mariadb: recommend enabling log_slave_updates when source is replica

.github/workflows/trademark-cla-approval.yml
Issue:
```
Available outputs:
pr_number: '4116'
pr_author: 'contributor-test-user'
approved_by: 'contributor-test-user'
Created new cla-signatures.json file
Recording manual trademark addendum approval:
Username: contributor-test-user
PR Number: 4116
Approved by: contributor-test-user
Date: 2025-07-19T18:26:13Z
New trademark adendum signature added
[main 50b3b31af] Add manual approval for @contributor-test-user (PR #4116) by @contributor-test-user
1 file changed, 10 insertions(+)
create mode 100644 cla-signatures.json
remote: Permission to ClickHouse/clickhouse-docs.git denied to workflow-authentication-public[bot].
fatal: unable to access 'https://github.com/ClickHouse/clickhouse-docs/': The requested URL returned error: 403
```
Fixed. The workflow now configures git to use the …
=> Legal: fix token issue when trying to push changes to repo

docs/integrations/data-ingestion/clickpipes/secure-rds.md, sidebars.js
For Postgres and MySQL ClickPipes, this will allow using IAM Auth for RDS and Aurora
=> feat(clickpipes): add aws iam db auth

docs/integrations/data-ingestion/aws-glue/index.md
=> Bug fix: Glue docs image doesn't load

src/theme/Tabs/styles.module.css
tabLists have an overflow inside of them 
https://github.com/user-attachments/assets/8ca9ffb4-b9bb-4362-8d04-18e6e9927b9e
=> Styling: fix tabList scrolling

src/components/DocsCategoryDropdown/index.jsx, src/components/DocsCategoryDropdown/styles.module.css
Fixes two issues:
- user needs to specifically click on the text of the navbar item to navigate
- the popup menu opens outside of the button
=> Styling: usability improvements to navbar

src/components/DocsCategoryDropdown/index.jsx, src/components/DocsCategoryDropdown/styles.module.css
Reverts ClickHouse/clickhouse-docs#4189
=> Revert "Styling: usability improvements to navbar"

docs/integrations/language-clients/java/client/_snippets/_v0_8.mdx, docs/integrations/language-clients/java/jdbc/_snippets/_v0_8.mdx
Updates version 
Add documentation for new config parameters
=> [Java] 0.9.1 Update

docs/integrations/data-ingestion/clickpipes/mongodb/datatypes.md, docs/integrations/data-ingestion/clickpipes/mongodb/index.md, docs/integrations/data-ingestion/clickpipes/mysql/datatypes.md
- Discovered a few nuance with data types that needs to be fixed in docs.
- ssh tunnel not currently supported for MongoDB, remove for now.
- Remove the redundant title `ClickPipes for MongoDB` (and MySQL too):
=> fix data type in documentation and remove ssh tunnel for now

src/theme/DocItem/TOC/Desktop/index.js
Fixes bug where galaxy events aren't getting pulled in because of incorrect import path.
=> Update index.js to fix galaxy events

docs/integrations/data-ingestion/clickpipes/object-storage.md
Fixed in [`clickpipes-platform` #4510](https://github.com/ClickHouse/clickpipes-platform/pull/4510).
@kitop: is it worth it to mention the possibility of double-counting, or still mention that as a limitation under certain scenarios?
=> clickpipes: remove limitation for object storage ClickPipe

scripts/search/index_pages.py
Fixes bug where keywords are not getting registered
=> Search: fix bug where keywords are not getting indexed

docs/cloud/security/setting-ip-filters.md
Clarify that IP access lists only apply outside of PrivateLink
=> Clarify that IP access lists only apply outside of PrivateLink

docs/data-modeling/backfilling.md, i18n/jp/docusaurus-plugin-content-docs/current/data-modeling/backfilling.md, i18n/ru/docusaurus-plugin-content-docs/current/data-modeling/backfilling.md, i18n/zh/docusaurus-plugin-content-docs/current/data-modeling/backfilling.md
Change `move partition from` to `move partition to` queries.
=> Fix backfilling manual

docs/data-compression/compression-in-clickhouse.md
Adds an explainer about wide vs compact parts to "Compression in ClickHouse".
Explains that you may see 0 bytes for compressed and uncompressed size if the part is compact.
Added an example to demonstrate.
=> Improvement: add explainer about wide vs compact parts to "Compression in ClickHouse"

docs/integrations/language-clients/java/client/_snippets/_v0_8.mdx, i18n/jp/docusaurus-plugin-content-docs/current/integrations/language-clients/java/client/_snippets/_v0_8.mdx, i18n/ru/docusaurus-plugin-content-docs/current/integrations/language-clients/java/client/_snippets/_v0_8.mdx, i18n/zh/docusaurus-plugin-content-docs/current/integrations/language-clients/java/client/_snippets/_v0_8.mdx
In [query method example](https://clickhouse.com/docs/integrations/language-clients/java/client#querystring-sqlquery-mapltstring-object-queryparams-querysettings-settings), QueryResponse argument passed to `newBinaryFormatReader` is named response, while the declared variable name is queryResponse.
This change updates the example for consistency between the variable declaration and its usage.
=> Fix wrong variable name in query example

docs/integrations/data-ingestion/kafka/confluent/confluent-cloud.md, vercel.json
Changes https://clickhouse.com/docs/integrations/kafka/cloud/confluent/custom-connector-cloud to https://clickhouse.com/docs/integrations/kafka/cloud/confluent/sink-connector and adds in a redirect.
=> Add redirect for kafka connect page

docs/integrations/data-ingestion/clickpipes/aws-privatelink.md
https://clickhouse-inc.slack.com/archives/C03A9B0H05T/p1755618535371819?thread_ts=1755618481.533949&cid=C03A9B0H05T
=> updating account id to use arn

docs/cloud/security/cmek.md
Updated the TDE section in the CMEK doc to make it explicit that:
- Once TDE is enabled, it cannot be disabled.
- If a customer wants to disable it, they must create a new instance and migrate data.
This change is intended to avoid confusion for users asking if TDE can be turned off.
=> Clarify TDE cannot be disabled once enabled

plugins/floating-pages-exceptions.txt, sidebars.js
The Arrow Flight page was added but never added to a sidebar.
=> Add Arrow Flight page to a sidebar

.github/CODEOWNERS
If I'm reading https://github.com/orgs/community/discussions/23644#discussioncomment-3241280 correctly, we should have ClickPipes entry as last, because it's a subpath for `/docs/integrations/`
=> fix: Correct CODEOWNERS entry order for ClickPipes documentation

i18n/jp/docusaurus-plugin-content-docs/current/materialized-view/refreshable-materialized-view.md
Fixes an issue where code blocks were not properly ended, causing a rendering issue.
=> Fix rendering issue in refreshable-materialized-view.md for Japanese translation

docs/integrations/language-clients/go/index.md
Fix some typos on ClickHouse Go doc page
=> Fix minor typos in ClickHouse go docs

contribute/style-guide.md, docs/integrations/data-ingestion/clickpipes/aws-privatelink.md, plugins/remark-custom-blocks.js, src/components/Stepper/Stepper.tsx
Adds support for using the `VerticalStepper` component with numbered lists. Updates the ClickPipes AWS Private Link page to use it.
=> Enhancement: support numbered lists for vertical stepper

plugins/floating-pages-exceptions.txt, sidebars.js
=> Add new allocation profiling page to sidebar

docs/getting-started/example-datasets/tpch.md
Since `25.8`, correlated subqueries are enabled by default in ClickHouse. Update TPC-H queries in the docs.
=> Update TPC-H docs

docs/cloud/onboard/02_migrate/01_migration_guides/04_snowflake/03_sql_translation_reference.md, docs/integrations/data-ingestion/data-formats/json/formats.md
Removes references to deprecated object type required to merge https://github.com/ClickHouse/ClickHouse/pull/85718
=> Docs: remove references to deprecated object type

docs/integrations/data-ingestion/clickpipes/mongodb/faq.md, docs/integrations/data-ingestion/clickpipes/mongodb/index.md, docs/integrations/data-ingestion/clickpipes/mongodb/quickstart.md, docs/integrations/data-ingestion/clickpipes/mysql/index.md, scripts/aspell-dict-file.txt, sidebars.js
- Update quick start documentation to provide example for incremental materialized view
- Add a FAQ section
- `_full_document` -> `doc`
- `private preview` -> `beta`
=> Update documentation for MongoDB clickpipes

docs/integrations/data-ingestion/clickpipes/postgres/faq.md
Adds to some existing FAQ sections in Postgres.
=> Postgres Pipes: Add more info in FAQ about replica identity and nulls in DELETEs

docs/cloud/guides/best_practices/usagelimits.md
=> only concurrency limits are per replica

README.md, docusaurus.config.en.js
- Allow skipping broken anchors check with 
```sh
ON_BROKEN_ANCHORS=ignore yarn build
```
- Added a README note
=> Allow configuring onBrokenAnchors for Docusaurus, add a README note

src/theme/SearchBar/utils/aiConflictHandler.js
A slightly less flaky fix for a previously flaky fix.
=> Bug fix: typing `/` while Ask AI widget is open triggers Docsearch pop-up (again)

knowledgebase/calculate-pi-using-sql.mdx
This PR fixes a minor typo in the Knowledge Base article
“Let’s calculate pi using SQL”: “mehthod” → “method”.
=> fix: typo “mehthod” → “method” in Pi article

knowledgebase/unable-to-access-cloud-service.mdx, src/components/KBArticleSearch/KBArticleSearch.js
Fixes a bug where multiple of the same KB article show in the search results.
=> Bug fix: duplicate KB articles show in search

docs/cloud/guides/security/cloud_access_management/saml-sso-setup.md
=> force load image

docs/cloud/features/04_infrastructure/byoc.md
=> Update BYOC Monitoring integration

docs/integrations/data-ingestion/dbms/postgresql/connecting-to-postgresql.md
This page says that it covers ClickPipes and PeerDB, but then only covers using the `PostgreSQL` table engine and the `MaterializedPostgreSQL` database engine.
Removed the note about covering ClickPipes and PeerDB and added a tip that if you're looking for a managed solution ClickPipes is a good option, otherwise OS PeerDB is an option.
=> Correct PostgreSQL integration page

docusaurus.config.en.js, docusaurus.config.jp.js, docusaurus.config.ru.js, docusaurus.config.zh.js, src/clientModules/utmPersistence.js
This PR adds persistence for UTM and tracking parameters on `.cloud` links to improve attribution.
Using the **MutationObserver API**, it watches for DOM changes and automatically appends collected parameters to `.cloud` links, specifically targeting `clickhouse.cloud/signup`.
- `utm_*` - Standard UTM parameters
- `utm_ga` - Google Analytics cookie ID
- `origPath` - First path the user landed on
- `pagePath` - Current page path
- `glxid` - Internal tracking ID
=> UTM Persistence for `.cloud` Links

scripts/search/index_pages.py, scripts/search/settings.json, src/theme/SearchBar/utils/searchConfig.js
Compute search is returning changelog before the reference material. Changelog should not be first.
Fixed so that doc_type ranking is taken into account in the algolia index.
=> adding doc_type ranking so references and guides appear first

scripts/search/index_pages.py, scripts/search/settings.json, src/theme/SearchBar/utils/searchConfig.js
post revert shenanigans, trying to implement changes again.
=> trying again, after reverts. tested against index locally.

docs/cloud/guides/SQL_console/_category_.json
Fixes the funny looking "SQL_console"
=> Improvement: add category file for SQL console dropdown
